import { describe, expect, it } from "vitest";
import type { GeneratedDocument } from "@/lib/generated-document";
import { applyVisibilityProfile, buildVisibleDocumentModel, createDefaultVisibility, normalizeDocumentVisibility } from "@/lib/document-visibility";
import { createInvoiceData } from "@/lib/invoice";

function invoiceDocument(): GeneratedDocument { const invoice=createInvoiceData(); invoice.company.name="Izdavatelj d.o.o.";invoice.customer.name="Kupac d.o.o.";invoice.customer.email="kupac@example.com";invoice.groups[0].items[0].name="Usluga";invoice.groups[0].items[0].unitPrice=100;return{type:"invoice",title:"Faktura",locale:"hr",fields:[],invoice,images:{logo:"logo",signature:"potpis",stamp:"pecat"}}; }
describe("global document visibility",()=>{
  it("normalizes old documents as fully visible",()=>{const document:GeneratedDocument={type:"cv",title:"CV",locale:"hr",fields:[{label:"Email",value:"a@b.hr"}]};const settings=normalizeDocumentVisibility(document);expect(settings.sections.fields.isVisible).toBe(true);expect(settings.sections.fields.fields.email.isVisible).toBe(true);});
  it("hides a whole customer without deleting source data",()=>{const source=invoiceDocument();const settings=createDefaultVisibility(source);settings.sections.customer.isVisible=false;source.visibility=settings;const visible=buildVisibleDocumentModel(source);expect(visible.invoice?.customer.name).toBe("");expect(source.invoice?.customer.name).toBe("Kupac d.o.o.");});
  it("hides only customer email",()=>{const source=invoiceDocument();const settings=createDefaultVisibility(source);settings.sections.customer.fields.email.isVisible=false;source.visibility=settings;const visible=buildVisibleDocumentModel(source);expect(visible.invoice?.customer.name).toBe("Kupac d.o.o.");expect(visible.invoice?.customer.email).toBe("");});
  it("hides an item and excludes it from calculation by default",()=>{const source=invoiceDocument();const item=source.invoice!.groups[0].items[0];const settings=createDefaultVisibility(source);settings.items[item.id]={isVisible:false,includeInCalculation:false};source.visibility=settings;const visible=buildVisibleDocumentModel(source);expect(visible.invoice?.groups[0].items[0].visible).toBe(false);expect(visible.invoice?.groups[0].items[0].includedInCalculation).toBe(false);expect(source.invoice?.groups[0].items[0].name).toBe("Usluga");});
  it("can hide an item but retain it in calculation",()=>{const source=invoiceDocument();const item=source.invoice!.groups[0].items[0];const settings=createDefaultVisibility(source);settings.items[item.id]={isVisible:false,includeInCalculation:true};source.visibility=settings;const visible=buildVisibleDocumentModel(source);expect(visible.invoice?.groups[0].items[0]).toMatchObject({visible:false,includedInCalculation:true});});
  it("hides signature, stamp and financial summary",()=>{const source=invoiceDocument();const settings=createDefaultVisibility(source);settings.sections.signatures.isVisible=false;settings.sections.stamp.isVisible=false;settings.sections.financials.isVisible=false;source.visibility=settings;const visible=buildVisibleDocumentModel(source);expect(visible.images?.signature).toBeUndefined();expect(visible.images?.stamp).toBeUndefined();expect(visible.invoice?.signatures).toEqual([]);expect(visible.invoice?.showFinancials).toBe(false);});
  it("serializes visibility with the document and restores it",()=>{const source=invoiceDocument();source.visibility=applyVisibilityProfile(createDefaultVisibility(source),"no-customer");const restored=JSON.parse(JSON.stringify(source)) as GeneratedDocument;expect(normalizeDocumentVisibility(restored).sections.customer.isVisible).toBe(false);expect(restored.invoice?.customer.name).toBe("Kupac d.o.o.");});
  it("keeps quantity visible in the no-prices profile",()=>{const settings=applyVisibilityProfile(createDefaultVisibility(),"no-prices");expect(settings.columns.find(v=>v.id==="quantity")?.isVisible).toBe(true);expect(settings.columns.find(v=>v.id==="price")?.isVisible).toBe(false);});
});
