import { describe, expect, it } from "vitest";
import { calculateInvoice, calculateProformaPayment, createInvoiceData, createInvoiceGroup, createInvoiceItem } from "@/lib/invoice";
function proforma(){const data=createInvoiceData();data.type="proforma";data.displayTitle="Predračun";data.groups[0].items[0]={...createInvoiceItem("one"),name:"Čelična usluga čćžšđ",unitPrice:100,taxRate:25};return data;}
describe("professional proforma",()=>{
  it("calculates one item and full payment in cents",()=>{const data=proforma();expect(calculateProformaPayment(data)).toMatchObject({totalCents:12500,dueCents:12500,remainingCents:0});});
  it("supports percentage and fixed advances",()=>{const data=proforma();data.paymentPlanMode="percentage";data.advancePercentage=30;expect(calculateProformaPayment(data).dueCents).toBe(3750);data.paymentPlanMode="fixed";data.advanceAmount=40;expect(calculateProformaPayment(data).dueCents).toBe(4000);});
  it("validates installments",()=>{const data=proforma();data.paymentPlanMode="installments";data.installments=[{id:"r1",name:"Rata 1",percentage:50,amount:62.5,dueDate:data.dueDate,activationCondition:"",note:"",status:"planirana",visible:true},{id:"r2",name:"Rata 2",percentage:50,amount:62.5,dueDate:data.dueDate,activationCondition:"",note:"",status:"planirana",visible:true}];expect(calculateProformaPayment(data).installmentsMatch).toBe(true);data.installments[1].amount=60;expect(calculateProformaPayment(data).installmentsMatch).toBe(false);});
  it("supports 30+ items, groups and multiple VAT rates",()=>{const data=proforma();data.groups=[createInvoiceGroup("Materijal","g1"),createInvoiceGroup("Rad","g2")];data.groups[0].items=Array.from({length:31},(_,index)=>({...createInvoiceItem(String(index)),unitPrice:10,taxRate:index%2?25:13}));data.groups[1].items=[{...createInvoiceItem("work"),unitPrice:50,taxRate:20}];const summary=calculateInvoice(data);expect(summary.totalCents).toBeGreaterThan(36000);expect(Object.keys(summary.taxByRate)).toEqual(expect.arrayContaining(["13","20","25"]));});
});
