"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { browserProjectStorage, LocalProjectRepository, ProjectService, type Project } from "@/lib/projects";

export function NewProjectForm() { const router = useRouter(); const service = useMemo(() => new ProjectService(new LocalProjectRepository(browserProjectStorage)), []); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(formData: FormData) { setSaving(true); setError(""); try { const now = new Date().toISOString(); const id = crypto.randomUUID(); const project: Project = { id, organizationId: "demo-org", code: String(formData.get("code")), name: String(formData.get("name")), description: String(formData.get("description")), projectType: String(formData.get("type")), status: "planned", priority: String(formData.get("priority")) as Project["priority"], address: String(formData.get("address")), city: String(formData.get("city")), postalCode: String(formData.get("postalCode")), country: "Hrvatska", startDate: String(formData.get("startDate")), expectedEndDate: String(formData.get("endDate")), contractValue: Number(formData.get("contractValue")), budget: Number(formData.get("budget")), currency: "EUR", progressPercent: 0, healthStatus: "on_track", riskLevel: "normal", createdAt: now, updatedAt: now, deletedAt: null }; await service.saveProject(project); router.push(`/projects/${id}/overview`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Projekt nije spremljen."); setSaving(false); } }
  return <main className="mx-auto max-w-4xl px-4 py-8 sm:px-8"><p className="text-sm font-semibold text-blue-600">Novi projekt</p><h1 className="mt-1 text-3xl font-semibold">Osnovni podaci gradilišta</h1><p className="mt-2 text-muted-foreground">Faze, zadatke, ekipu i materijale dodat ćete nakon kreiranja.</p><form action={submit} className="mt-7 grid gap-5 rounded-3xl border bg-card p-5 sm:grid-cols-2 sm:p-8">{field("Naziv projekta", "name", true)}{field("Kod projekta", "code", true)}{select("Vrsta", "type", ["građevinski", "sanacija", "renovacija", "održavanje", "instalacije", "infrastruktura", "privatni projekt", "poslovni projekt", "drugi"])}{select("Prioritet", "priority", ["normal", "high", "urgent", "critical", "low"])}{field("Adresa", "address", true)}{field("Grad", "city", true)}{field("Poštanski broj", "postalCode", true)}{field("Planirani početak", "startDate", true, "date")}{field("Planirani završetak", "endDate", true, "date")}{field("Ugovorena vrijednost", "contractValue", false, "number")}{field("Budžet", "budget", false, "number")}<label className="sm:col-span-2"><span className="mb-2 block text-sm font-medium">Opis</span><textarea name="description" rows={4} className="w-full rounded-xl border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></label>{error && <p className="sm:col-span-2 text-sm text-red-600">{error}</p>}<div className="flex gap-3 sm:col-span-2"><button disabled={saving} className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-50">{saving ? "Spremanje…" : "Kreiraj projekt"}</button><button type="button" onClick={() => router.back()} className="rounded-xl border px-5 py-3 text-sm font-semibold">Odustani</button></div></form></main>; }
function field(label: string, name: string, required = false, type = "text") { return <label><span className="mb-2 block text-sm font-medium">{label}</span><input name={name} type={type} required={required} min={type === "number" ? 0 : undefined} className="h-11 w-full rounded-xl border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></label>; }
function select(label: string, name: string, options: string[]) { return <label><span className="mb-2 block text-sm font-medium">{label}</span><select name={name} className="h-11 w-full rounded-xl border bg-background px-3 text-sm">{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
