import { Check, ChevronDown, Download, Eye, FileText, Palette, Type } from "lucide-react";

export function ProductEditorShowcase() {
  return <section className="overflow-hidden bg-slate-950 py-20 text-white sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-8 lg:px-10">
    <div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[.18em] text-blue-400">Stvarni način rada</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">Sve promjene odmah vidite na dokumentu.</h2><p className="mt-5 text-lg text-slate-400">Forma, izgled papira i A4 pregled rade zajedno — bez prelaska između nepovezanih alata.</p></div>
    <div className="relative mt-12 rounded-[1.75rem] border border-white/10 bg-slate-900 p-2 shadow-2xl sm:p-4"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-3 py-3"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-blue-600"><FileText className="size-4"/></span><div><b className="block text-sm">Ponuda za hidroizolaciju</b><span className="text-xs text-emerald-400">● Sve promjene spremljene lokalno</span></div></div><div className="flex gap-2"><button className="rounded-lg border border-white/15 px-3 py-2 text-xs"><Eye className="mr-1 inline size-3"/> Pregled</button><button className="rounded-lg bg-blue-600 px-3 py-2 text-xs"><Download className="mr-1 inline size-3"/> PDF / Word</button></div></div>
      <div className="grid gap-3 p-2 sm:p-3 lg:grid-cols-[230px_1fr_1.08fr]"><aside className="hidden rounded-2xl border border-white/10 bg-slate-950/70 p-3 lg:block"><p className="px-2 text-[10px] font-bold uppercase tracking-wider text-slate-500">Sekcije</p>{["Osnovni podaci","Klijent","Stavke","Financije","Uvjeti","Potpisi"].map((item,index)=><div key={item} className={`mt-2 flex items-center justify-between rounded-xl px-3 py-2.5 text-xs ${index===2?"bg-blue-600 text-white":"text-slate-400"}`}><span>{item}</span>{index<2?<Check className="size-3 text-emerald-400"/>:<span>{index+1}</span>}</div>)}</aside>
        <div className="rounded-2xl border border-white/10 bg-slate-950/50 p-3 sm:p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-blue-400">Uređivanje forme</p><h3 className="mt-1 font-semibold">Stavke ponude</h3></div><ChevronDown className="size-4"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Opis","Hidroizolacija podruma"],["Količina","120"],["Jedinica","m²"],["Cijena","28,00 €"]].map(([label,value])=><label key={label} className="text-xs text-slate-400">{label}<span className="mt-1.5 block rounded-xl border border-white/10 bg-slate-900 px-3 py-3 text-sm text-white">{value}</span></label>)}</div><div className="mt-4 rounded-xl border border-dashed border-blue-400/30 p-3 text-center text-xs text-blue-300">+ Dodaj novu stavku</div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 p-3"><Palette className="size-4 text-blue-400"/><b className="mt-2 block text-xs">Corporate Blue</b><span className="text-[10px] text-slate-500">Tema dokumenta</span></div><div className="rounded-xl border border-white/10 p-3"><Type className="size-4 text-blue-400"/><b className="mt-2 block text-xs">Inter + Source Sans</b><span className="text-[10px] text-slate-500">Tipografija</span></div></div></div>
        <div className="rounded-2xl bg-slate-800 p-3 sm:p-5"><div className="mx-auto aspect-[210/260] max-w-sm overflow-hidden rounded bg-[#f8fbff] p-[7%] text-slate-900 shadow-2xl"><div className="h-2 w-24 rounded bg-blue-600"/><div className="mt-5 flex items-start justify-between"><div><div className="text-xs font-bold">DEMO GRADNJA d.o.o.</div><div className="mt-1 text-[7px] text-slate-500">Zagreb · demo@primjer.local</div></div><span className="rounded bg-blue-600 px-2 py-1 text-[8px] font-bold text-white">PONUDA</span></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded border border-blue-100 bg-blue-50 p-2"><b className="block text-[8px]">Za klijenta</b><span className="text-[7px] text-slate-500">Primjer Projekt d.o.o.</span></div><div className="rounded border p-2"><b className="block text-[8px]">Vrijedi do</b><span className="text-[7px] text-slate-500">31. 8. 2026.</span></div></div><table className="mt-5 w-full text-[7px]"><thead className="bg-blue-600 text-white"><tr><th className="p-2 text-left">Opis</th><th>Količina</th><th>Iznos</th></tr></thead><tbody><tr className="border-b"><td className="p-2">Hidroizolacija podruma</td><td className="text-center">120 m²</td><td className="text-right">3.360,00 €</td></tr><tr className="border-b bg-blue-50/60"><td className="p-2">Priprema podloge</td><td className="text-center">1 usl.</td><td className="text-right">450,00 €</td></tr></tbody></table><div className="ml-auto mt-5 w-32 rounded border border-blue-100 bg-blue-50 p-3 text-[7px]"><div className="flex justify-between"><span>PDV</span><b>952,50 €</b></div><div className="mt-2 flex justify-between border-t border-blue-200 pt-2 text-[9px]"><span>Ukupno</span><b>4.762,50 €</b></div></div></div></div>
      </div>
    </div>
  </div></section>;
}
