"use client";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { Copy, Eye, EyeOff, ImagePlus, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { DocumentLocale, GeneratedDocument } from "@/lib/generated-document";
import { calculateCompletedWorksSummary, completedWorksFields, completedWorksSectionLabels, createCompletedWorksReport, createReportRecord, createWorkPhase, recalculateWork, type CompletedWorksReportData, type CompletedWorksSectionId, type ReportRecord } from "@/lib/completed-works-report";

type Props={locale:DocumentLocale;onPreview:(document:GeneratedDocument)=>void;onLiveChange?:(document:GeneratedDocument)=>void};
const input="h-10 w-full rounded-xl border bg-background px-3 text-sm";
const recordSections=(Object.keys(completedWorksSectionLabels) as CompletedWorksSectionId[]).filter(v=>!['photos','phases'].includes(v)) as Exclude<CompletedWorksSectionId,'photos'|'phases'>[];
const move=<T,>(items:T[],index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=items.length)return items;const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next};
export function CompletedWorksReportForm({locale,onPreview,onLiveChange}:Props){
 const [data,setData]=useState<CompletedWorksReportData>(createCompletedWorksReport);
 const summary=useMemo(()=>calculateCompletedWorksSummary(data),[data]);
 const generated=useMemo<GeneratedDocument>(()=>({type:'completed-works-report',title:'Izvještaj o izvedenim radovima',locale,fields:[],completedWorksReport:data}),[data,locale]);
 useEffect(()=>onLiveChange?.(generated),[generated,onLiveChange]);
 const set=<K extends keyof CompletedWorksReportData>(key:K,value:CompletedWorksReportData[K])=>setData(current=>({...current,[key]:value}));
 const setRecords=(id:Exclude<CompletedWorksSectionId,'photos'|'phases'>,value:ReportRecord[])=>setData(current=>({...current,sections:{...current.sections,[id]:value}}));
 async function addPhotos(files:FileList|null){if(!files)return;const loaded=await Promise.all([...files].map(file=>new Promise<CompletedWorksReportData['photos'][number]>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve({id:crypto.randomUUID(),title:file.name,description:'',dateTime:new Date().toISOString().slice(0,16),location:'',phase:'',relatedWork:'',state:'tijekom',dataUrl:String(reader.result),visible:true});reader.readAsDataURL(file)})));set('photos',[...data.photos,...loaded])}
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();onPreview(generated)}}>
  <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Faze" value={summary.phases}/><Metric label="Radovi" value={summary.works}/><Metric label="Radnici" value={summary.workers}/><Metric label="Radni sati" value={summary.workHours}/></div>
  <Section title="Osnovni podaci izvještaja" open><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
   <Field label="Broj izvještaja" value={data.number} onChange={v=>set('number',v)}/><Field label="Prilagodljivi format" value={data.numberFormat} onChange={v=>set('numberFormat',v)}/><Field label="Datum izdavanja" type="date" value={data.issueDate} onChange={v=>set('issueDate',v)}/><Field label="Razdoblje od" type="date" value={data.periodFrom} onChange={v=>set('periodFrom',v)}/><Field label="Razdoblje do" type="date" value={data.periodTo} onChange={v=>set('periodTo',v)}/>
   {(['projectName','siteName','siteAddress','investor','customer','mainContractor','subcontractor','supervision','siteManager','foreman','responsiblePerson','contractNumber','orderNumber','workOrderNumber','offerNumber','projectPhase'] as const).map(key=><Field key={key} label={({projectName:'Projekt',siteName:'Gradilište',siteAddress:'Adresa gradilišta',investor:'Investitor',customer:'Naručitelj',mainContractor:'Glavni izvođač',subcontractor:'Podizvođač',supervision:'Nadzor',siteManager:'Voditelj gradilišta',foreman:'Poslovođa',responsiblePerson:'Odgovorna osoba',contractNumber:'Broj ugovora',orderNumber:'Broj narudžbenice',workOrderNumber:'Broj radnog naloga',offerNumber:'Broj ponude',projectPhase:'Faza projekta'} as const)[key]} value={data[key]} onChange={v=>set(key,v)}/>) }
   <Select label="Status" value={data.status} options={['nacrt','pripremljen','poslan','pregledan','prihvaćen','prihvaćen uz napomenu','odbijen','vraćen na doradu','arhiviran']} onChange={v=>set('status',v)}/><Select label="A4 predložak" value={data.template} options={['classic','modern','executive']} onChange={v=>set('template',v as CompletedWorksReportData['template'])}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={data.showFinancials} onChange={e=>set('showFinancials',e.target.checked)}/>Prikaži financijske podatke</label>
  </div></Section>
  <Section title="Faze i grupe radova"><div className="space-y-2">{data.phases.map((phase,index)=><div key={phase.id} className={`flex flex-wrap items-center gap-2 rounded-xl border p-3 ${phase.visible?'':'opacity-50'}`}><input className={`${input} min-w-52 flex-1`} value={phase.title} onChange={e=>set('phases',data.phases.map(v=>v.id===phase.id?{...v,title:e.target.value}:v))}/><label className="text-xs"><input type="checkbox" checked={phase.showSubtotal} onChange={e=>set('phases',data.phases.map(v=>v.id===phase.id?{...v,showSubtotal:e.target.checked}:v))}/> Međuzbroj</label><Icon title="Vidljivost" onClick={()=>set('phases',data.phases.map(v=>v.id===phase.id?{...v,visible:!v.visible}:v))}>{phase.visible?<Eye/>:<EyeOff/>}</Icon><Icon title="Dupliciraj" onClick={()=>set('phases',[...data.phases.slice(0,index+1),{...structuredClone(phase),id:crypto.randomUUID()},...data.phases.slice(index+1)])}><Copy/></Icon><Icon title="Gore" onClick={()=>set('phases',move(data.phases,index,-1))}>↑</Icon><Icon title="Dolje" onClick={()=>set('phases',move(data.phases,index,1))}>↓</Icon><Icon title="Obriši" onClick={()=>confirm('Obrisati fazu?')&&set('phases',data.phases.filter(v=>v.id!==phase.id))}><Trash2/></Icon></div>)}<Button type="button" variant="outline" onClick={()=>set('phases',[...data.phases,createWorkPhase('Nova faza')])}><Plus/>Dodaj fazu</Button></div></Section>
  {recordSections.map(id=><RecordSection key={id} id={id} values={data.sections[id]} phases={data.phases.map(v=>v.title)} showFinancials={data.showFinancials} onChange={v=>setRecords(id,v)}/>) }
  <Section title="Fotografije izvedenih radova"><div className="flex flex-wrap gap-3"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border px-4 py-2 text-sm"><ImagePlus className="size-4"/>Dodaj fotografije<input type="file" accept="image/*" multiple className="sr-only" onChange={e=>addPhotos(e.target.files)}/></label><Select label="Izgled galerije" value={data.photoLayout} options={['one','two','four','comparison','gallery']} onChange={v=>set('photoLayout',v as CompletedWorksReportData['photoLayout'])}/></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{data.photos.map((photo,index)=><div key={photo.id} className={`rounded-xl border p-3 ${photo.visible?'':'opacity-50'}`}><Image src={photo.dataUrl} alt={photo.title} width={640} height={360} unoptimized className="h-40 w-full rounded-lg object-cover"/>{(['title','description','dateTime','location','phase','relatedWork','state'] as const).map(key=><Field key={key} label={({title:'Naslov',description:'Opis',dateTime:'Datum i vrijeme',location:'Lokacija',phase:'Faza',relatedWork:'Povezani rad',state:'Stanje'} as const)[key]} value={photo[key]} onChange={value=>set('photos',data.photos.map(v=>v.id===photo.id?{...v,[key]:value}:v))}/>) }<div className="flex gap-1"><Icon title="Vidljivost" onClick={()=>set('photos',data.photos.map(v=>v.id===photo.id?{...v,visible:!v.visible}:v))}>{photo.visible?<Eye/>:<EyeOff/>}</Icon><Icon title="Dupliciraj" onClick={()=>set('photos',[...data.photos.slice(0,index+1),{...structuredClone(photo),id:crypto.randomUUID()},...data.photos.slice(index+1)])}><Copy/></Icon><Icon title="Gore" onClick={()=>set('photos',move(data.photos,index,-1))}>↑</Icon><Icon title="Dolje" onClick={()=>set('photos',move(data.photos,index,1))}>↓</Icon><Icon title="Obriši" onClick={()=>confirm('Obrisati fotografiju?')&&set('photos',data.photos.filter(v=>v.id!==photo.id))}><Trash2/></Icon></div></div>)}</div></Section>
  <Button type="submit" className="w-full">Pregledaj izvještaj</Button>
 </form>
}
function RecordSection({id,values,phases,showFinancials,onChange}:{id:Exclude<CompletedWorksSectionId,'photos'|'phases'>;values:ReportRecord[];phases:string[];showFinancials:boolean;onChange:(v:ReportRecord[])=>void}){const fields=completedWorksFields[id].filter(field=>showFinancials||!['jedinična cijena','PDV %','procijenjena vrijednost','iznos'].includes(field));return <Section title={completedWorksSectionLabels[id]}><div className="space-y-3">{values.map((record,index)=><div key={record.id} className={`rounded-xl border p-3 ${record.visible?'':'opacity-50'}`}><div className="mb-3 flex flex-wrap items-center gap-2"><input className={`${input} min-w-48 flex-1 font-medium`} value={record.title} onChange={e=>onChange(values.map(v=>v.id===record.id?{...v,title:e.target.value}:v))}/><label className="text-xs"><input type="checkbox" checked={record.includeInStatistics} onChange={e=>onChange(values.map(v=>v.id===record.id?{...v,includeInStatistics:e.target.checked}:v))}/> Statistika/obračun</label><Icon title="Vidljivost" onClick={()=>onChange(values.map(v=>v.id===record.id?{...v,visible:!v.visible}:v))}>{record.visible?<Eye/>:<EyeOff/>}</Icon><Icon title="Dupliciraj" onClick={()=>onChange([...values.slice(0,index+1),{...structuredClone(record),id:crypto.randomUUID()},...values.slice(index+1)])}><Copy/></Icon><Icon title="Gore" onClick={()=>onChange(move(values,index,-1))}>↑</Icon><Icon title="Dolje" onClick={()=>onChange(move(values,index,1))}>↓</Icon><Icon title="Obriši" onClick={()=>confirm('Obrisati zapis?')&&onChange(values.filter(v=>v.id!==record.id))}><Trash2/></Icon></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{fields.map(field=>field==='faza'?<Select key={field} label="Faza" value={String(record.fields[field]??'')} options={['',...phases]} onChange={value=>onChange(values.map(v=>v.id===record.id?{...v,fields:{...v.fields,[field]:value}}:v))}/>:<Field key={field} label={field} value={String(record.fields[field]??'')} type={/(datum|količina|sati|cijena|vrijednost|PDV|iznos|završenost)/i.test(field)?'number':'text'} onChange={value=>onChange(values.map(v=>v.id===record.id?(id==='works'?recalculateWork({...v,fields:{...v.fields,[field]:value}}):{...v,fields:{...v.fields,[field]:value}}):v))}/>)}</div></div>)}<Button type="button" variant="outline" onClick={()=>onChange([...values,createReportRecord(id)])}><Plus/>Dodaj zapis</Button></div></Section>}
function Section({title,open=false,children}:{title:string;open?:boolean;children:React.ReactNode}){return <details open={open} className="rounded-2xl border bg-card"><summary className="cursor-pointer px-4 py-3 font-semibold">{title}</summary><div className="border-t p-4">{children}</div></details>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="grid gap-1 text-xs font-medium capitalize">{label}<input className={input} type={type} step={type==='number'?'any':undefined} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="grid gap-1 text-xs font-medium">{label}<select className={input} value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v} value={v}>{v||'Odaberite'}</option>)}</select></label>}
function Icon({title,onClick,children}:{title:string;onClick:()=>void;children:React.ReactNode}){return <button type="button" title={title} aria-label={title} className="inline-flex size-9 items-center justify-center rounded-lg border [&_svg]:size-4" onClick={onClick}>{children}</button>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border bg-muted/40 p-3"><div className="text-xl font-bold">{Math.round(value*100)/100}</div><div className="text-xs text-muted-foreground">{label}</div></div>}
