import Image from "next/image";
import { calculateCompletedWorksSummary, completedWorksSectionLabels, type CompletedWorksReportData, type CompletedWorksSectionId } from "@/lib/completed-works-report";
import { formatDocumentDate } from "@/lib/generated-document";
const colors={classic:{accent:'#1e3a5f',soft:'#e8eef4'},modern:{accent:'#0f766e',soft:'#e6fffb'},executive:{accent:'#312e81',soft:'#eef2ff'}};
export function CompletedWorksReportSheet({data,compact=false}:{data:CompletedWorksReportData;compact?:boolean}){const summary=calculateCompletedWorksSummary(data),theme=colors[data.template];return <article className={`min-h-[297mm] bg-white text-slate-900 ${compact?'p-5 text-[8px]':'p-[14mm] text-[9px]'}`} style={{'--report-accent':theme.accent,'--report-soft':theme.soft} as React.CSSProperties}>
 <header className="flex justify-between gap-6 border-b-4 pb-4" style={{borderColor:theme.accent}}><div><div className="text-xl font-bold">IZVJEŠTAJ O IZVEDENIM RADOVIMA</div><div className="mt-1 text-sm font-semibold">{data.projectName||'Naziv projekta'}</div><div className="text-slate-500">{[data.siteName,data.siteAddress].filter(Boolean).join(' · ')}</div></div><div className="text-right"><div className="text-base font-bold" style={{color:theme.accent}}>{data.number}</div><div>{formatDocumentDate(data.issueDate,'hr')}</div><div className="mt-1 rounded-full px-3 py-1 font-semibold" style={{background:theme.soft}}>{data.status}</div></div></header>
 <div className="mt-4 grid grid-cols-2 gap-x-6 gap-y-1"><Meta label="Razdoblje" value={`${formatDocumentDate(data.periodFrom,'hr')} – ${formatDocumentDate(data.periodTo,'hr')}`}/>{[['Investitor',data.investor],['Naručitelj',data.customer],['Glavni izvođač',data.mainContractor],['Podizvođač',data.subcontractor],['Nadzor',data.supervision],['Voditelj gradilišta',data.siteManager],['Broj ugovora',data.contractNumber],['Faza projekta',data.projectPhase]].map(([l,v])=><Meta key={l} label={l} value={v}/>)}</div>
 <div className="my-4 grid grid-cols-4 gap-2">{[['Faze',summary.phases],['Radovi',summary.works],['Završeno',summary.completed],['Prosjek',`${summary.averageCompletion.toFixed(1)}%`],['Radnici',summary.workers],['Radni sati',summary.workHours],['Otvoreni nedostaci',summary.openDefects],['Dodatni radovi',summary.additionalWorks]].map(([l,v])=><div key={l} className="rounded p-2 text-center" style={{background:theme.soft}}><b className="block text-sm">{v}</b><span>{l}</span></div>)}</div>
 {data.phases.filter(v=>v.visible).length>0&&<ReportTable title="Faze i grupe radova" rows={data.phases.filter(v=>v.visible).map(v=>[v.title,v.showSubtotal?'Prikaži međuzbroj':'Bez međuzbroja'])}/>} 
 {(Object.keys(data.sections) as Exclude<CompletedWorksSectionId,'photos'|'phases'>[]).map(id=>{const records=data.sections[id].filter(v=>v.visible);if(!records.length)return null;return <ReportTable key={id} title={completedWorksSectionLabels[id]} rows={records.map(record=>[record.title,Object.entries(record.fields).filter(([key,v])=>String(v)!==''&&(data.showFinancials||!/(cijena|vrijednost|PDV|iznos)/i.test(key))).map(([k,v])=>`${k}: ${v}`).join(' · ')])}/>})}
 {data.showFinancials&&<section className="ml-auto mt-4 w-72 rounded border p-3 text-right"><div>Vrijednost bez PDV-a: <b>{summary.net.toFixed(2)} €</b></div><div>PDV: <b>{summary.tax.toFixed(2)} €</b></div><div className="mt-1 text-sm" style={{color:theme.accent}}>Ukupno: <b>{summary.total.toFixed(2)} €</b></div></section>}
 {data.photos.filter(v=>v.visible).length>0&&<section className="mt-5 break-before-auto"><Heading>Fotografije izvedenih radova</Heading><div className={`grid gap-3 ${data.photoLayout==='one'?'grid-cols-1':data.photoLayout==='four'?'grid-cols-2':'grid-cols-2'}`}>{data.photos.filter(v=>v.visible).map(photo=><figure key={photo.id} className="break-inside-avoid rounded border p-2"><Image src={photo.dataUrl} alt={photo.title} width={800} height={500} unoptimized className="h-40 w-full object-contain"/><figcaption className="mt-1"><b>{photo.title}</b><br/>{[photo.description,photo.location,photo.state].filter(Boolean).join(' · ')}</figcaption></figure>)}</div></section>}
 <footer className="mt-8 border-t pt-2 text-slate-500"><span>{data.projectName||'Izvještaj o izvedenim radovima'}</span><span className="float-right">Stranica</span></footer>
 </article>}
function Meta({label,value}:{label:string;value:string}){if(!value)return null;return <div><span className="text-slate-500">{label}: </span><b>{value}</b></div>}
function Heading({children}:{children:React.ReactNode}){return <h2 className="mb-2 mt-4 border-b pb-1 text-xs font-bold uppercase" style={{color:'var(--report-accent)'}}>{children}</h2>}
function ReportTable({title,rows}:{title:string;rows:string[][]}){return <section className="break-inside-auto"><Heading>{title}</Heading><table className="w-full border-collapse"><thead className="table-header-group"><tr className="text-left text-white" style={{background:'var(--report-accent)'}}><th className="w-1/4 p-2">Zapis</th><th className="p-2">Detalji</th></tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="break-inside-avoid border-b"><td className="p-2 align-top font-semibold">{row[0]}</td><td className="p-2 align-top leading-relaxed">{row[1]}</td></tr>)}</tbody></table></section>}
