"use client";

import Image from "next/image";
import { calculatePurchaseOrderItem, calculatePurchaseOrderTotals, type PurchaseOrderData, type PurchaseOrderParty } from "@/lib/purchase-order";
import { formatDocumentDate, type GeneratedImages } from "@/lib/generated-document";

export function PurchaseOrderSheet({ data, images, compact = false }: { data: PurchaseOrderData; images?: GeneratedImages; compact?: boolean }) {
  const totals = calculatePurchaseOrderTotals(data.items);
  const money = (value: number) => { try { return new Intl.NumberFormat("hr-HR", { style: "currency", currency: data.currency || "EUR" }).format(value); } catch { return `${value.toFixed(2)} ${data.currency}`; } };
  return <article className={`relative mx-auto flex w-full max-w-[210mm] flex-col bg-white text-slate-900 ${compact ? "h-full min-h-full p-[5%] text-[5.5px]" : "min-h-[297mm] px-[14mm] py-[12mm] text-[10px]"}`}>
    <header className="flex items-start justify-between gap-5 border-b-2 border-slate-800 pb-3"><div className="flex min-h-10 items-start gap-3">{images?.logo && <Image src={images.logo} alt="Logotip naručitelja" width={compact ? 60 : 110} height={compact ? 24 : 42} unoptimized className="max-h-11 max-w-28 object-contain" />}<PartyBlock party={data.buyer} /></div><div className="text-right"><h1 className={compact ? "text-[13px] font-bold" : "text-2xl font-bold tracking-tight"}>NARUDŽBENICA</h1><p className="mt-1 font-semibold">Br. {data.orderNumber || "—"}</p><p>{formatDocumentDate(data.issueDate, "hr")} {data.issuePlace && `· ${data.issuePlace}`}</p></div></header>
    <section className="mt-3 grid grid-cols-2 gap-3"><Box title="DOBAVLJAČ"><PartyBlock party={data.supplier} /></Box><Box title="ISPORUKA I PLAĆANJE"><Meta label="Željena isporuka" value={formatDocumentDate(data.desiredDeliveryDate, "hr")} /><Meta label="Mjesto isporuke" value={data.deliveryPlace} /><Meta label="Način isporuke" value={data.deliveryMethod} /><Meta label="Rok / način plaćanja" value={[data.paymentDeadline, data.paymentMethod].filter(Boolean).join(" · ")} /></Box></section>
    {(data.offerReference || data.project || data.responsiblePerson) && <section className="mt-3 grid grid-cols-3 gap-2 rounded border bg-slate-50 p-2"><Meta label="Referenca ponude" value={data.offerReference} /><Meta label="Projekt / gradilište" value={data.project} /><Meta label="Odgovorna osoba" value={data.responsiblePerson} /></section>}
    <table className="mt-3 w-full table-fixed border-collapse"><thead className="[display:table-header-group]"><tr className="bg-slate-800 text-white"><th className="w-[5%] p-1.5 text-center">R.br.</th><th className={data.showPrices ? "w-[35%] p-1.5 text-left" : "w-[77%] p-1.5 text-left"}>Naziv / opis</th><th className="w-[9%] p-1.5 text-right">Kol.</th><th className="w-[9%] p-1.5 text-center">JM</th>{data.showPrices && <><th className="w-[12%] p-1.5 text-right">Cijena</th><th className="w-[8%] p-1.5 text-right">Popust</th><th className="w-[7%] p-1.5 text-right">PDV</th><th className="w-[15%] p-1.5 text-right">Iznos</th></>}</tr></thead><tbody>{data.items.map((item, index) => { const amounts = calculatePurchaseOrderItem(item); return <tr key={item.id} className="break-inside-avoid border-b border-slate-300 align-top"><td className="p-1.5 text-center">{index + 1}</td><td className="p-1.5 font-medium">{item.name || "—"}{item.description && <span className="mt-0.5 block font-normal text-slate-500">{item.description}</span>}</td><td className="p-1.5 text-right">{item.quantity}</td><td className="p-1.5 text-center">{item.unit}</td>{data.showPrices && <><td className="p-1.5 text-right">{money(item.unitPrice)}</td><td className="p-1.5 text-right">{item.discountRate}%</td><td className="p-1.5 text-right">{item.taxRate}%</td><td className="p-1.5 text-right font-semibold">{money(amounts.total)}</td></>}</tr>; })}</tbody></table>
    {data.showPrices && <dl className="ml-auto mt-3 w-[48%] space-y-1"><Total label="Ukupno bez PDV-a" value={money(totals.gross)} /><Total label="Popust" value={`− ${money(totals.discount)}`} /><Total label="Porezna osnovica" value={money(totals.subtotal)} /><Total label="PDV" value={money(totals.tax)} /><div className="flex justify-between border-t-2 border-slate-800 pt-1.5 text-[1.15em] font-bold"><dt>Ukupno s PDV-om</dt><dd>{money(totals.total)}</dd></div></dl>}
    <div className="mt-4 space-y-2">{data.note && <Note title="NAPOMENA" value={data.note} />}{data.deliveryTerms && <Note title="UVJETI ISPORUKE" value={data.deliveryTerms} />}{data.paymentTerms && <Note title="UVJETI PLAĆANJA" value={data.paymentTerms} />}</div>
    <section className="mt-5 grid grid-cols-3 gap-3 break-inside-avoid">{[["NARUČIO", data.orderedBy], ["ODOBRIO", data.approvedBy], ["DOBAVLJAČ / POTVRDA PRIMITKA", data.supplierConfirmation]].map(([title, signature]) => { const entry = signature as PurchaseOrderData["orderedBy"]; return <div key={title as string} className="min-h-20 border-t border-slate-500 pt-2 text-center"><p className="font-bold">{title as string}</p><p className="mt-2">{entry.name}</p><p className="text-slate-500">{entry.role}</p><p>{formatDocumentDate(entry.date, "hr")}</p></div>; })}</section>
    {(images?.signature || images?.stamp) && <div className="mt-2 flex justify-end gap-4 break-inside-avoid">{images.signature && <Image src={images.signature} alt="Potpis" width={100} height={40} unoptimized className="h-10 max-w-24 object-contain" />}{images.stamp && <Image src={images.stamp} alt="Pečat" width={70} height={50} unoptimized className="h-12 max-w-16 object-contain" />}</div>}
    <footer className="mt-auto flex justify-between border-t pt-2 text-slate-500"><span>{data.buyer.name || "Narudžbenica"}</span><span>Stranica 1</span></footer>
  </article>;
}

function PartyBlock({ party }: { party: PurchaseOrderParty }) { return <div><strong className="text-[1.15em]">{party.name}</strong>{party.address && <p>{party.address}</p>}{party.cityPostalCode && <p>{party.cityPostalCode}</p>}{party.taxNumber && <p>OIB / PIB: {party.taxNumber}</p>}{party.contactPerson && <p>Kontakt: {party.contactPerson}</p>}{(party.phone || party.email) && <p>{[party.phone, party.email].filter(Boolean).join(" · ")}</p>}</div>; }
function Box({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded border border-slate-300 p-2"><h2 className="mb-1.5 border-b pb-1 font-bold tracking-wide">{title}</h2>{children}</div>; }
function Meta({ label, value }: { label: string; value: string }) { return value ? <p><span className="text-slate-500">{label}: </span>{value}</p> : null; }
function Total({ label, value }: { label: string; value: string }) { return <div className="flex justify-between"><dt>{label}</dt><dd>{value}</dd></div>; }
function Note({ title, value }: { title: string; value: string }) { return <section className="break-inside-avoid rounded border border-slate-300 p-2"><h2 className="font-bold">{title}</h2><p className="mt-1 whitespace-pre-wrap">{value}</p></section>; }
