"use client";
import { useMemo,useRef,useState } from "react";
import { Copy,Eye,EyeOff,GripVertical,Lock,Plus,Redo2,Search,Trash2,Undo2,Unlock } from "lucide-react";
import { addBlock,blockRegistry,deleteBlock,duplicateBlock,emptyComposer,moveBlock,updateBlock,type ComposerDocument,type ContentBlock } from "@/lib/composer";
export function ComposerPanel({value,onChange}:{value?:ComposerDocument;onChange:(value:ComposerDocument)=>void}){
 const composer=value??emptyComposer(),[query,setQuery]=useState(""),[selected,setSelected]=useState<string>(),[library,setLibrary]=useState(false),[history,setHistory]=useState<ComposerDocument[]>([]),[future,setFuture]=useState<ComposerDocument[]>([]),drag=useRef<string|undefined>(undefined);
 const shown=useMemo(()=>blockRegistry.filter(v=>`${v.label} ${v.keywords.join(" ")}`.toLocaleLowerCase("hr").includes(query.toLocaleLowerCase("hr"))),[query]);
 function commit(next:ComposerDocument){setHistory(current=>[...current.slice(-49),structuredClone(composer)]);setFuture([]);onChange(next)}
 function undo(){const previous=history.at(-1);if(!previous)return;setHistory(v=>v.slice(0,-1));setFuture(v=>[...v,structuredClone(composer)]);onChange(previous)}
 function redo(){const next=future.at(-1);if(!next)return;setFuture(v=>v.slice(0,-1));setHistory(v=>[...v,structuredClone(composer)]);onChange(next)}
 function remove(id:string){if(!confirm("Obrisati blok? Radnju možete vratiti s Undo."))return;commit(deleteBlock(composer,id));setSelected(undefined)}
 return <section className="mb-5 overflow-hidden rounded-2xl border bg-card"><div className="flex flex-wrap items-center gap-2 border-b p-3"><div><b className="text-sm">Document Composer</b><p className="text-xs text-muted-foreground">{composer.blocks.length} blokova · automatsko spremanje</p></div><button type="button" onClick={()=>setLibrary(v=>!v)} className="ml-auto inline-flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground"><Plus className="size-3.5"/>Dodaj sadržaj</button><button type="button" onClick={undo} disabled={!history.length} className="rounded-lg border p-2 disabled:opacity-30" aria-label="Undo Composer"><Undo2 className="size-4"/></button><button type="button" onClick={redo} disabled={!future.length} className="rounded-lg border p-2 disabled:opacity-30" aria-label="Redo Composer"><Redo2 className="size-4"/></button></div>
 {library&&<div className="border-b bg-muted/30 p-3"><label className="flex h-10 items-center gap-2 rounded-xl border bg-background px-3"><Search className="size-4"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pretraži blokove…" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><div className="mt-3 grid max-h-64 gap-2 overflow-y-auto sm:grid-cols-2">{shown.map(def=><button type="button" draggable key={def.type} onDragStart={e=>e.dataTransfer.setData("application/x-document-block",def.type)} onClick={()=>{commit(addBlock(composer,def.type));setLibrary(false)}} className="rounded-xl border bg-background p-3 text-left hover:border-primary"><b className="block text-sm">{def.label}</b><span className="text-xs text-muted-foreground">{def.category}</span></button>)}</div></div>}
 <div className="p-3" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const type=e.dataTransfer.getData("application/x-document-block");if(type)commit(addBlock(composer,type as Parameters<typeof addBlock>[1]))}}>{!composer.blocks.length?<button type="button" onClick={()=>setLibrary(true)} className="w-full rounded-2xl border border-dashed p-10 text-sm text-muted-foreground">Dodaj prvi sadržajni blok</button>:<div className="space-y-2">{composer.blocks.map((block,index)=><BlockRow key={block.id} block={block} selected={selected===block.id} select={()=>setSelected(block.id)} dragStart={()=>{drag.current=block.id}} drop={()=>{const id=drag.current;if(id)commit(moveBlock(composer,id,index));drag.current=undefined}} update={patch=>commit(updateBlock(composer,block.id,patch))} up={()=>commit(moveBlock(composer,block.id,index-1))} down={()=>commit(moveBlock(composer,block.id,index+1))} duplicate={()=>commit(duplicateBlock(composer,block.id))} remove={()=>remove(block.id)}/>)}</div>}</div></section>
}
function BlockRow({block,selected,select,dragStart,drop,update,up,down,duplicate,remove}:{block:ContentBlock;selected:boolean;select():void;dragStart():void;drop():void;update(patch:Partial<ContentBlock>):void;up():void;down():void;duplicate():void;remove():void}){const text=String(block.content.text??block.content.value??block.content.title??"");return <article draggable={block.locked!=="position"&&block.locked!=="readonly"} onDragStart={dragStart} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();drop()}} onClick={select} className={`rounded-xl border p-3 transition ${selected?"border-primary ring-2 ring-primary/15":"hover:border-primary/40"} ${block.visible?"":"opacity-55"}`}><div className="flex items-center gap-2"><GripVertical className="size-4 cursor-grab text-muted-foreground"/><div className="min-w-0 flex-1"><b className="block truncate text-sm">{block.name}</b><span className="text-[11px] text-muted-foreground">{block.type} · {block.layout.width}</span></div><button type="button" onClick={e=>{e.stopPropagation();update({visible:!block.visible})}} className="rounded-lg p-2 hover:bg-muted" aria-label={block.visible?"Sakrij blok":"Prikaži blok"}>{block.visible?<Eye className="size-4"/>:<EyeOff className="size-4"/>}</button><button type="button" onClick={e=>{e.stopPropagation();update({locked:block.locked==="none"?"position":"none"})}} className="rounded-lg p-2 hover:bg-muted" aria-label={block.locked==="none"?"Zaključaj poziciju":"Otključaj"}>{block.locked==="none"?<Unlock className="size-4"/>:<Lock className="size-4"/>}</button></div>{selected&&<div className="mt-3 border-t pt-3" onClick={e=>e.stopPropagation()}>{["text","rich-text","subtitle","document-title","note","warning","legal","terms","custom"].includes(block.type)&&<textarea value={text} onChange={e=>update({content:{...block.content,text:e.target.value}})} rows={3} className="w-full rounded-xl border bg-background p-3 text-sm" aria-label="Sadržaj bloka"/>}<div className="mt-2 flex flex-wrap gap-1"><button type="button" onClick={up} className="rounded-lg border px-2 py-1 text-xs">Gore</button><button type="button" onClick={down} className="rounded-lg border px-2 py-1 text-xs">Dolje</button><button type="button" onClick={duplicate} className="inline-flex items-center gap-1 rounded-lg border px-2 py-1 text-xs"><Copy className="size-3"/>Dupliciraj</button><select value={block.layout.width} onChange={e=>update({layout:{...block.layout,width:e.target.value as ContentBlock["layout"]["width"]}})} className="rounded-lg border bg-background px-2 text-xs" aria-label="Širina bloka"><option value="full">Puna širina</option><option value="half">1/2</option><option value="third">1/3</option><option value="30">30%</option><option value="70">70%</option></select><button type="button" onClick={remove} className="ml-auto inline-flex items-center gap-1 rounded-lg border border-red-200 px-2 py-1 text-xs text-red-600"><Trash2 className="size-3"/>Obriši</button></div></div>}</article>}
