"use client";

import { useState } from "react";
import { Building2, ImagePlus, Save, ShieldAlert } from "lucide-react";
import { WorkspaceHeader } from "@/components/workspace/workspace-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLocalSession } from "@/components/session/local-session-provider";
import { useRepositories } from "@/lib/data/use-local-data";
import { demoCompany } from "@/lib/data/demo-data";
import type { Company } from "@/lib/data/models";

const fields: Array<[keyof Company,string,string?]> = [["companyName","Naziv firme"],["address","Adresa"],["city","Grad"],["postalCode","Poštanski broj"],["country","Država"],["taxNumber","OIB / PIB"],["vatNumber","PDV broj"],["registrationNumber","Matični broj"],["iban","IBAN"],["swift","SWIFT"],["bankName","Banka"],["phone","Telefon"],["email","Email","email"],["website","Web stranica","url"],["responsiblePerson","Odgovorna osoba"]];

function CompanyForm({ initial, onSave }: { initial: Company; onSave: (company: Company) => void }) { const [company,setCompany] = useState(initial); const [message,setMessage] = useState(""); function update(key: keyof Company,value:string) { setCompany((current) => ({...current,[key]:value})); } function image(key: "logoUrl"|"signatureUrl"|"stampUrl", file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => update(key,String(reader.result)); reader.readAsDataURL(file); } return <form onSubmit={(event) => { event.preventDefault(); onSave(company); setMessage("Podaci firme spremljeni su lokalno."); }} className="mt-7 space-y-7"><section className="rounded-3xl border bg-card p-6"><h2 className="font-semibold">Osnovni i financijski podaci</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">{fields.map(([key,label,type]) => <div key={key} className={key === "companyName" || key === "address" ? "sm:col-span-2" : ""}><label htmlFor={`company-${key}`} className="mb-2 block text-sm font-semibold">{label}</label><Input id={`company-${key}`} type={type} value={String(company[key])} onChange={(event) => update(key,event.target.value)} required={key === "companyName"} /></div>)}</div></section><section className="rounded-3xl border bg-card p-6"><h2 className="font-semibold">Vizualni elementi</h2><div className="mt-5 grid gap-4 sm:grid-cols-3">{([['logoUrl','Logotip'],['signatureUrl','Potpis'],['stampUrl','Pečat']] as const).map(([key,label]) => <label key={key} className="cursor-pointer rounded-2xl border border-dashed p-5 text-center transition hover:border-primary hover:bg-muted"><ImagePlus className="mx-auto size-5 text-primary" /><span className="mt-2 block text-sm font-semibold">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{company[key] ? "Slika dodana" : "PNG ili JPG"}</span><input type="file" accept="image/png,image/jpeg" className="sr-only" onChange={(event) => image(key,event.target.files?.[0])} /></label>)}</div></section>{message && <p role="status" className="rounded-xl bg-emerald-500/10 p-3 text-sm text-emerald-700">{message}</p>}<Button type="submit"><Save className="size-4" /> Spremi podatke firme</Button></form>; }

export function CompanyPage() { const repositories = useRepositories(); const { user } = useLocalSession(); if (!repositories) return <><WorkspaceHeader title="Podaci firme" /><div className="skeleton mx-auto mt-10 h-96 max-w-5xl rounded-3xl" /></>; const company = repositories.companies.getByUser(user.id) ?? {...demoCompany,id:"",userId:user.id,companyName:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; return <><WorkspaceHeader title="Podaci firme" /><main className="mx-auto max-w-5xl px-4 py-8 sm:px-7"><div className="flex items-start gap-4"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><Building2 /></span><div><h1 className="text-3xl font-semibold">Podaci firme</h1><p className="mt-2 text-muted-foreground">Ovi podaci automatski se nude pri izradi novih dokumenata.</p></div></div><div className="mt-6 flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100"><ShieldAlert className="mt-0.5 size-5 shrink-0" /><p>LocalStorage nije produkcijska baza. U ovoj fazi koristite samo demo ili testne podatke.</p></div><CompanyForm initial={company} onSave={(value) => repositories.companies.save(value)} /></main></>; }
