import type { EntitlementKey, PlanDefinition, PlanId, UsageKey } from "./types";
const allFalse = Object.fromEntries(["createDocument","useAI","exportPDF","exportDOCX","removeBranding","premiumTemplates","customTemplates","multipleCompanies","inviteTeamMembers","advancedAnalytics","versionHistory","cloudStorage","documentConversion","bulkExport","prioritySupport","auditLog"].map((key) => [key, false])) as Record<EntitlementKey, boolean>;
const limits = (values: Partial<Record<UsageKey, number>>) => ({ documents: 0, savedDocuments: 0, aiActions: 0, aiCredits: 0, pdfExports: 0, docxExports: 0, companies: 0, contacts: 0, projects: 0, teamMembers: 1, storageBytes: 0, attachments: 0, customTemplates: 0, documentVersions: 0, conversions: 0, bulkOperations: 0, ...values });
const features = (...enabled: EntitlementKey[]) => ({ ...allFalse, ...Object.fromEntries(enabled.map((key) => [key, true])) });
export const planCatalog: Record<PlanId, PlanDefinition> = {
  free: { id: "free", name: "Free", description: "Za povremenu izradu osnovnih dokumenata.", trialDays: 0, prices: { month: { amountMinor: 0, currency: "EUR" }, year: { amountMinor: 0, currency: "EUR" } }, entitlements: features("createDocument","useAI","exportPDF"), limits: limits({ documents: 3, savedDocuments: 3, aiActions: 5, aiCredits: 5, pdfExports: 5, docxExports: 0, companies: 1, contacts: 20, projects: 1, storageBytes: 25_000_000, attachments: 5 }), highlights: ["3 dokumenta mjesečno", "5 AI akcija", "PDF izvoz", "1 korisnik i 1 firma", "Dokument AI oznaka"] },
  basic: { id: "basic", name: "Basic", description: "Za samostalne profesionalce i male obrte.", trialDays: 7, prices: { month: { amountMinor: 1200, currency: "EUR", priceEnv: "STRIPE_PRICE_BASIC_MONTHLY" }, year: { amountMinor: 12000, currency: "EUR", priceEnv: "STRIPE_PRICE_BASIC_YEARLY" } }, entitlements: features("createDocument","useAI","exportPDF","exportDOCX","removeBranding","premiumTemplates","cloudStorage"), limits: limits({ documents: 30, savedDocuments: 100, aiActions: 50, aiCredits: 75, pdfExports: 100, docxExports: 30, companies: 1, contacts: 250, projects: 10, storageBytes: 500_000_000, attachments: 100, customTemplates: 2, documentVersions: 3 }), highlights: ["30 dokumenata mjesečno", "50 AI akcija", "PDF i DOCX", "Cloud spremanje", "Bez brandinga"] },
  pro: { id: "pro", name: "Pro", description: "Za tvrtke koje svakodnevno rade s dokumentima.", recommended: true, trialDays: 14, prices: { month: { amountMinor: 2900, currency: "EUR", priceEnv: "STRIPE_PRICE_PRO_MONTHLY" }, year: { amountMinor: 29000, currency: "EUR", priceEnv: "STRIPE_PRICE_PRO_YEARLY" } }, entitlements: features("createDocument","useAI","exportPDF","exportDOCX","removeBranding","premiumTemplates","customTemplates","multipleCompanies","inviteTeamMembers","advancedAnalytics","versionHistory","cloudStorage","documentConversion","prioritySupport"), limits: limits({ documents: 200, savedDocuments: 2_000, aiActions: 500, aiCredits: 800, pdfExports: 1_000, docxExports: 1_000, companies: 5, contacts: 5_000, projects: 200, teamMembers: 3, storageBytes: 5_000_000_000, attachments: 2_000, customTemplates: 100, documentVersions: 50, conversions: 100 }), highlights: ["200 dokumenata mjesečno", "500 AI akcija", "Napredni Template Engine", "Verzioniranje i analitika", "3 člana tima"] },
  business: { id: "business", name: "Business", description: "Za timove, organizacije i naprednu administraciju.", trialDays: 14, prices: { month: { amountMinor: 7900, currency: "EUR", priceEnv: "STRIPE_PRICE_BUSINESS_MONTHLY" }, year: { amountMinor: 79000, currency: "EUR", priceEnv: "STRIPE_PRICE_BUSINESS_YEARLY" } }, entitlements: features("createDocument","useAI","exportPDF","exportDOCX","removeBranding","premiumTemplates","customTemplates","multipleCompanies","inviteTeamMembers","advancedAnalytics","versionHistory","cloudStorage","documentConversion","bulkExport","prioritySupport","auditLog"), limits: limits({ documents: 2_000, savedDocuments: 20_000, aiActions: 5_000, aiCredits: 10_000, pdfExports: 10_000, docxExports: 10_000, companies: 100, contacts: 100_000, projects: 5_000, teamMembers: 25, storageBytes: 50_000_000_000, attachments: 50_000, customTemplates: 2_000, documentVersions: 500, conversions: 2_000, bulkOperations: 500 }), highlights: ["Visoki organizacijski limiti", "25 uključenih mjesta", "Uloge i zajednički resursi", "Audit log i bulk operacije", "Prioritetna podrška"] },
};
export const getPlan = (id: PlanId) => planCatalog[id];
export const billingAICreditLimits = { free: 30, basic: 300, pro: 3_000, business: 30_000 } as const;
export function annualSavings(id: PlanId) { const plan = getPlan(id); const monthlyYear = plan.prices.month.amountMinor * 12; const annual = plan.prices.year.amountMinor; return { amountMinor: Math.max(0, monthlyYear - annual), percent: monthlyYear ? Math.round((1 - annual / monthlyYear) * 100) : 0 }; }
