-- FUTURE SUPABASE SCHEMA ONLY. Do not execute in the current local-demo phase.
-- The active application adapter is local and does not connect to Supabase.

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, first_name text not null default '', last_name text not null default '', language text not null default 'hr', country text not null default '', plan text not null default 'free', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.companies (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, company_name text not null, logo_url text, address text, city text, postal_code text, country text, tax_number text, vat_number text, registration_number text, iban text, swift text, bank_name text, phone text, email text, website text, responsible_person text, signature_url text, stamp_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.contacts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, company_name text not null, contact_name text, address text, city text, postal_code text, country text, tax_number text, email text, phone text, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.documents (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, company_id uuid references public.companies(id) on delete set null, contact_id uuid references public.contacts(id) on delete set null, document_type text not null, document_category text not null, title text not null, document_number text, status text not null default 'draft', language text not null default 'hr', currency text not null default 'EUR', subtotal numeric(14,2) not null default 0, tax_amount numeric(14,2) not null default 0, total numeric(14,2) not null default 0, form_data jsonb not null default '{}', content jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), last_opened_at timestamptz);
create table public.document_items (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.documents(id) on delete cascade, position integer not null default 0, description text not null, quantity numeric(14,3) not null default 1, unit_price numeric(14,2) not null default 0, tax_rate numeric(6,3) not null default 0, amount numeric(14,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.document_exports (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.documents(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, format text not null check (format in ('pdf','docx')), created_at timestamptz not null default now());

create index companies_user_id_idx on public.companies(user_id); create index contacts_user_id_idx on public.contacts(user_id); create index documents_user_updated_idx on public.documents(user_id,updated_at desc); create index documents_user_status_idx on public.documents(user_id,status); create index document_items_document_idx on public.document_items(document_id,position); create index document_exports_document_idx on public.document_exports(document_id,created_at desc);

alter table public.profiles enable row level security; alter table public.companies enable row level security; alter table public.contacts enable row level security; alter table public.documents enable row level security; alter table public.document_items enable row level security; alter table public.document_exports enable row level security;

-- RLS draft for the future Supabase adapter:
-- profiles: auth.uid() = id
-- companies/contacts/documents/document_exports: auth.uid() = user_id
-- document_items: document belongs to auth.uid()
-- Add explicit SELECT/INSERT/UPDATE/DELETE policies before enabling the adapter.
