"use client";

import { useMemo, useState } from "react";
import { Clock3, Download, FileCheck2, FilePlus2, Gauge, LogOut, ShieldCheck } from "lucide-react";
import { AnalyticsFilters } from "./analytics-filters";
import { MetricCard, RankedList, TrendChart } from "./analytics-visuals";
import { createDemoAnalyticsEvents } from "@/lib/analytics/demo-data";
import { calculateAnalyticsMetrics, filterAnalyticsEvents } from "@/lib/analytics/metrics";
import type { AnalyticsFilter } from "@/lib/analytics/types";

const initialFilter: AnalyticsFilter = { period: "90d", documentType: "all", category: "all", language: "all", device: "all", completion: "all", exportType: "all" };

export function AnalyticsDashboard() {
  const [filter, setFilter] = useState(initialFilter); const demoEvents = useMemo(() => createDemoAnalyticsEvents(), []); const events = useMemo(() => filterAnalyticsEvents(demoEvents, filter), [demoEvents, filter]); const metrics = useMemo(() => calculateAnalyticsMetrics(events), [events]);
  return <div className="mx-auto max-w-[1600px] px-4 py-8 sm:px-7 lg:px-10"><header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-primary"><Gauge className="size-4" /> Administratorska analitika · demo adapter</div><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Korištenje dokumenata</h1><p className="mt-2 max-w-2xl text-muted-foreground">Agregirani događaji bez sadržaja dokumenta i osobnih podataka.</p></div><div className="flex items-center gap-2 rounded-xl border bg-emerald-500/5 px-4 py-3 text-sm text-emerald-700 dark:text-emerald-300"><ShieldCheck className="size-4" /> Privacy-safe događaji</div></header><div className="mt-7"><AnalyticsFilters value={filter} onChange={setFilter} /></div><section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-7"><MetricCard label="Započeti" value={metrics.started} note="document_started" Icon={FilePlus2} /><MetricCard label="Završeni" value={metrics.completed} note="document_completed" Icon={FileCheck2} /><MetricCard label="PDF izvoz" value={metrics.pdfExports} note="Preuzimanja" Icon={Download} /><MetricCard label="DOCX izvoz" value={metrics.docxExports} note="Preuzimanja" Icon={Download} /><MetricCard label="Stopa završavanja" value={`${metrics.completionRate}%`} note="Završeni / započeti" Icon={Gauge} /><MetricCard label="Stopa odustajanja" value={`${metrics.abandonmentRate}%`} note="Napušteni / započeti" Icon={LogOut} /><MetricCard label="Prosječno vrijeme" value={`${Math.floor(metrics.averageDurationSeconds / 60)}m ${metrics.averageDurationSeconds % 60}s`} note="Do završetka" Icon={Clock3} /></section><section className="mt-5 grid gap-5 lg:grid-cols-3"><RankedList title="Najkorištenije vrste" rows={metrics.topTypes} /><RankedList title="Najkorištenije kategorije" rows={metrics.topCategories} /><RankedList title="Najkorišteniji predlošci" rows={metrics.topTemplates} /></section><section className="mt-5 grid gap-5 lg:grid-cols-2"><RankedList title="Korištenje po jeziku" rows={metrics.byLanguage} /><RankedList title="Korištenje po uređaju" rows={metrics.byDevice} /></section><section className="mt-5 grid gap-5 xl:grid-cols-3"><TrendChart title="Trend po danima" data={metrics.dailyTrend} /><TrendChart title="Trend po tjednima" data={metrics.weeklyTrend} /><TrendChart title="Trend po mjesecima" data={metrics.monthlyTrend} /></section><section className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-5"><RankedList title="Najviše započeti" rows={metrics.mostStarted} /><RankedList title="Najviše završeni" rows={metrics.mostCompleted} /><RankedList title="Najviše izvoženi" rows={metrics.mostExported} /><RankedList title="Najveće odustajanje" rows={metrics.highestAbandonment} suffix="%" /><RankedList title="Najbrže rastući" rows={metrics.fastestGrowing} suffix="%" /></section></div>;
}
