import type { DocumentTemplate } from "./types";
const names = ["Classic", "Modern", "Corporate", "Construction", "Minimal", "Executive", "Dark Header", "Blue Corporate", "Elegant", "Simple", "Professional", "Technical", "Premium", "Clean", "Document AI Default"] as const;
const palettes = [["#1e3a5f", "#e8eef4"], ["#0f766e", "#e6fffb"], ["#334155", "#f1f5f9"], ["#b45309", "#fffbeb"], ["#111827", "#f9fafb"], ["#312e81", "#eef2ff"], ["#0f172a", "#e2e8f0"], ["#1d4ed8", "#eff6ff"], ["#7c2d12", "#fff7ed"], ["#374151", "#f9fafb"], ["#075985", "#f0f9ff"], ["#475569", "#f8fafc"], ["#6d28d9", "#f5f3ff"], ["#166534", "#f0fdf4"], ["#2563eb", "#eff6ff"]] as const;
const now = "2026-01-01T00:00:00.000Z";
export const defaultSections = ["header", "document", "parties", "content", "items", "financials", "notes", "signatures", "footer"].map((label, order) => ({ id: label, label: label[0].toUpperCase() + label.slice(1), order, columns: 1 as const, visible: true, duplicable: !["header", "footer"].includes(label) }));
export const builtInTemplates: DocumentTemplate[] = names.map((name, index) => {
  const [accent, soft] = palettes[index];
  return { version: 1, id: name.toLowerCase().replaceAll(" ", "-"), name, description: `${name} profesionalni A4 predložak`, documentTypes: ["all"], builtIn: true, createdAt: now, updatedAt: now,
    theme: { mode: name === "Dark Header" ? "dark" : "light", font: index % 3 === 0 ? "Roboto" : index % 3 === 1 ? "Inter" : "Noto Sans", fontSize: index === 4 ? 9 : 10, fontWeight: 400, textColor: "#0f172a", accentColor: accent, headingColor: accent, tableHeaderColor: accent, tableRowColor: "#ffffff", alternateRowColor: soft, backgroundColor: "#ffffff", lineColor: accent, lineWidth: index === 9 ? 0.5 : 1, borderRadius: index % 4 === 0 ? 0 : 6, spacing: index === 4 ? 8 : 12 },
    page: { size: "A4", orientation: "portrait", margins: { top: 14, right: 14, bottom: 14, left: 14 } }, header: { layout: index === 8 ? "centered" : index === 4 ? "minimal" : "logo-company-document", logoPosition: "left", companyPosition: "left", documentNumberPosition: "right", showQr: false, showBarcode: false, height: 24 }, footer: { position: "center", showPageNumber: true, pageNumberPosition: "right", fields: ["email", "phone", "web"], note: "" }, assets: { logoIds: [], stampIds: [], signatureIds: [], logoPosition: "left", signaturePosition: "right", stampPosition: "right" }, sections: structuredClone(defaultSections), table: { headerVisible: true, alternatingRows: index % 2 === 0, padding: 6, rowHeight: 24, columnOrder: [] } };
});
export const DEFAULT_TEMPLATE_ID = "document-ai-default";
