"use client";

import { useMemo, useState } from "react";
import { Eye, Plus, Save, Trash2 } from "lucide-react";
import { updateGeneratedDocument } from "@/app/dashboard/actions";
import { DocumentPreview } from "@/components/generator/document-preview";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { GeneratedDocument } from "@/lib/generated-document";

export function DocumentEditor({ id, initialDocument }: { id: string; initialDocument: GeneratedDocument }) {
  const [document, setDocument] = useState(initialDocument); const [preview, setPreview] = useState(false); const [message, setMessage] = useState("");
  const totals = useMemo(() => { if (!document.items || !document.totals) return document.totals; const subtotal = document.items.reduce((sum, item) => sum + item.quantity * item.price, 0); const tax = subtotal * document.totals.taxRate / 100; return { ...document.totals, subtotal, tax, total: subtotal + tax }; }, [document.items, document.totals]);
  const current = { ...document, totals };
  async function save() { const result = await updateGeneratedDocument(id, current); setMessage(result.error ?? "Promjene su spremljene."); }
  return <><div className="space-y-7"><div><label className="mb-2 block text-sm font-semibold">Naziv dokumenta</label><Input value={document.title} onChange={(event) => setDocument((value) => ({ ...value, title: event.target.value }))} /></div><div className="grid gap-5 sm:grid-cols-2">{document.fields.map((field, index) => <div key={`${field.label}-${index}`} className={field.type === "multiline" ? "sm:col-span-2" : undefined}><label className="mb-2 block text-sm font-semibold">{field.label}</label>{field.type === "multiline" ? <Textarea value={field.value} onChange={(event) => setDocument((value) => ({ ...value, fields: value.fields.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item) }))} /> : <Input type={field.type === "date" ? "date" : "text"} value={field.value} onChange={(event) => setDocument((value) => ({ ...value, fields: value.fields.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item) }))} />}</div>)}</div>{document.items && <section className="border-t pt-7"><div className="flex justify-between"><h2 className="font-semibold">Stavke</h2><Button type="button" size="sm" variant="outline" onClick={() => setDocument((value) => ({ ...value, items: [...(value.items ?? []), { description: "", quantity: 1, price: 0, amount: 0 }] }))}><Plus className="size-4" /> Stavka</Button></div><div className="mt-4 space-y-3">{document.items.map((item, index) => <div key={index} className="grid gap-3 rounded-xl border bg-slate-50 p-3 sm:grid-cols-[1fr_100px_120px_auto]"><Input value={item.description} onChange={(event) => setDocument((value) => ({ ...value, items: value.items?.map((line, lineIndex) => lineIndex === index ? { ...line, description: event.target.value } : line) }))} /><Input type="number" value={item.quantity} onChange={(event) => setDocument((value) => ({ ...value, items: value.items?.map((line, lineIndex) => lineIndex === index ? { ...line, quantity: Number(event.target.value) } : line) }))} /><Input type="number" value={item.price} onChange={(event) => setDocument((value) => ({ ...value, items: value.items?.map((line, lineIndex) => lineIndex === index ? { ...line, price: Number(event.target.value) } : line) }))} /><Button variant="ghost" size="icon" onClick={() => setDocument((value) => ({ ...value, items: value.items?.filter((_, lineIndex) => lineIndex !== index) }))}><Trash2 className="size-4 text-red-600" /></Button></div>)}</div></section>}{message && <p className="rounded-xl bg-blue-50 p-3 text-sm text-blue-900">{message}</p>}<div className="flex flex-wrap justify-end gap-3 border-t pt-6"><Button variant="outline" onClick={() => setPreview(true)}><Eye className="size-4" /> Pregled i izvoz</Button><Button onClick={save}><Save className="size-4" /> Spremi promjene</Button></div></div>{preview && <DocumentPreview document={current} documentId={id} onClose={() => setPreview(false)} />}</>;
}
