import type { AIDocumentDraft, AIFieldSuggestion } from "./types";
export type AIDiff = { field: string; before: unknown; after: unknown; reason: string; confidence: number; sensitive: boolean; accepted: boolean };
const sensitiveFields = /price|tax|date|oib|pib|iban|name|number|amount|total/i;
export function createDiff(current: Record<string, unknown>, suggestions: AIFieldSuggestion[]): AIDiff[] { return suggestions.filter((item) => item.value !== null && current[item.field] !== item.value).map((item) => ({ field: item.field, before: current[item.field] ?? null, after: item.value, reason: item.reason, confidence: item.confidence, sensitive: sensitiveFields.test(item.field), accepted: false })); }
export function applyDiff<T extends Record<string, unknown>>(current: T, diff: AIDiff[], acceptedFields: Set<string>): { next: T; undo: T } { const undo = structuredClone(current); const next = structuredClone(current); diff.filter((change) => acceptedFields.has(change.field)).forEach((change) => { next[change.field as keyof T] = change.after as T[keyof T]; }); return { next, undo }; }
export function convertDraft(source: AIDocumentDraft, targetType: string): AIDocumentDraft { return structuredClone({ ...source, metadata: { ...source.metadata, documentType: targetType, title: `${source.metadata.title} — kopija`, category: ["invoice", "proforma", "offer", "purchase-order"].includes(targetType) ? "finance" : source.metadata.category }, warnings: [...source.warnings, "Konverzija je pripremljena kao nova kopija; original nije promijenjen."] }); }
export function validateDraft(draft: AIDocumentDraft) { const issues = [...draft.validationIssues]; if (["invoice", "proforma", "offer", "purchase-order"].includes(draft.metadata.documentType) && !draft.metadata.currency) issues.push({ level: "error" as const, field: "currency", message: "Financijski dokument mora imati valutu." }); draft.items.forEach((item) => { if (item.quantity > 0 && !item.unit) issues.push({ level: "warning", field: "unit", message: `Stavka ${item.name} ima količinu bez jedinice.` }); }); return issues; }
export const protectedTranslationPatterns = [/\bHR\d{19}\b/g, /\b\d{11}\b/g, /\b[A-Z]{2}\d{2}[A-Z0-9]{10,30}\b/g, /\b[A-Z]{2,5}-\d{2,}\b/g, /\b\d+(?:[.,]\d+)?\s?(?:EUR|USD|€)\b/g];

