import Link from "next/link";
import { ArrowRight, BarChart3, Clock3, Copy, FilePlus2, FileText, Search, Sparkles, Star, Trash2, TrendingUp } from "lucide-react";

import { deleteDocument, toggleFavorite } from "@/app/dashboard/actions";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { documentTypeDefinitions, isDocumentType } from "@/lib/document-types";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
const currentMonth = new Date().toISOString().slice(0, 7);

type Row = { id: string; title: string; type: string; created_at: string; updated_at: string; is_favorite: boolean; open_count: number };

function DocumentCard({ document }: { document: Row }) {
  return <article className="group rounded-2xl border bg-card p-4 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-primary/30 hover:shadow-xl">
    <div className="flex items-start justify-between gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><FileText className="size-5" /></span><form action={toggleFavorite}><input type="hidden" name="id" value={document.id} /><input type="hidden" name="favorite" value={String(document.is_favorite)} /><button className="rounded-lg p-2 hover:bg-muted" aria-label={document.is_favorite ? "Ukloni iz omiljenih" : "Dodaj u omiljene"}><Star className={`size-4 ${document.is_favorite ? "fill-amber-400 text-amber-400" : "text-muted-foreground"}`} /></button></form></div>
    <p className="mt-4 text-xs font-semibold uppercase tracking-wider text-primary">{documentTypeDefinitions[document.type as keyof typeof documentTypeDefinitions]?.label ?? document.type}</p><h3 className="mt-1 truncate font-semibold">{document.title}</h3><p className="mt-2 flex items-center gap-1.5 text-xs text-muted-foreground"><Clock3 className="size-3.5" /> {new Intl.DateTimeFormat("hr-HR", { dateStyle: "medium" }).format(new Date(document.updated_at))}</p>
    <div className="mt-4 flex items-center gap-1 border-t pt-3"><Link href={`/dashboard/documents/${document.id}`} className={buttonVariants({ variant: "ghost", size: "sm" })}>Otvori <ArrowRight className="size-3.5" /></Link><form action={deleteDocument} className="ml-auto"><input type="hidden" name="id" value={document.id} /><Button type="submit" variant="ghost" size="icon" aria-label={`Obriši ${document.title}`}><Trash2 className="size-4 text-red-500" /></Button></form></div>
  </article>;
}

export default async function DashboardPage({ searchParams }: PageProps<"/dashboard">) {
  const params = await searchParams; const query = typeof params.q === "string" ? params.q.trim() : ""; const type = typeof params.type === "string" && isDocumentType(params.type) ? params.type : ""; const sort = params.sort === "oldest" || params.sort === "type" ? params.sort : "newest"; const favoritesOnly = params.view === "favorites";
  const supabase = await createClient(); let request = supabase.from("documents").select("id,title,type,created_at,updated_at,is_favorite,open_count");
  if (query) request = request.ilike("title", `%${query.replace(/[%_]/g, "\\$&")}%`); if (type) request = request.eq("type", type); if (favoritesOnly) request = request.eq("is_favorite", true);
  request = sort === "type" ? request.order("type").order("updated_at", { ascending: false }) : request.order("updated_at", { ascending: sort === "oldest" });
  const { data } = await request; const documents = (data ?? []) as Row[];
  const recent = documents.slice(0, 6); const favorites = documents.filter((item) => item.is_favorite).slice(0, 4); const frequent = [...documents].sort((a, b) => b.open_count - a.open_count).slice(0, 4); const thisMonth = documents.filter((item) => item.created_at.startsWith(currentMonth)).length;
  const stats = [{ label: "Ukupno dokumenata", value: documents.length, Icon: FileText, help: "Svi spremljeni dokumenti" }, { label: "Ovaj mjesec", value: thisMonth, Icon: TrendingUp, help: "Novi dokumenti" }, { label: "Omiljeni", value: favorites.length, Icon: Star, help: "Brzi pristup" }, { label: "Aktivnost", value: documents.reduce((n, d) => n + d.open_count, 0), Icon: BarChart3, help: "Ukupno otvaranja" }];
  const quickActions = [{ label: "Nova faktura", type: "invoice", Icon: FilePlus2 }, { label: "Nova ponuda", type: "offer", Icon: Sparkles }, { label: "Novi CV", type: "cv", Icon: Copy }];
  return <main className="mx-auto max-w-[1500px] px-4 py-7 sm:px-7 lg:px-9">
    <section className="relative overflow-hidden rounded-3xl bg-slate-950 p-6 text-white shadow-2xl sm:p-9"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-blue-500/25 blur-3xl" /><div className="relative flex flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-sm text-blue-300"><Sparkles className="size-4" /> Pametni dokument wizard</div><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Šta želiš napraviti danas?</h1><p className="mt-3 max-w-xl text-slate-300">Opišite dokument, odgovorite na pitanja jedno po jedno i pratite kako nastaje uživo.</p></div><Link href="/wizard" className={buttonVariants({ size: "lg" })}><Sparkles className="size-4" /> Pokreni Smart Wizard</Link></div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, Icon, help }) => <article key={label} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><span className="rounded-xl bg-primary/10 p-2 text-primary"><Icon className="size-4" /></span></div><p className="mt-3 text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{help}</p></article>)}</section>
    <section className="mt-6 grid gap-5 xl:grid-cols-[1fr_320px]"><div className="rounded-3xl border bg-card p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">{favoritesOnly ? "Omiljeni dokumenti" : "Nedavni dokumenti"}</h2><p className="mt-1 text-sm text-muted-foreground">Nastavite tamo gdje ste stali.</p></div><Link href="/generator" className={buttonVariants({ variant: "outline", size: "sm" })}>Prikaži predloške</Link></div><form className="mt-5 grid gap-3 sm:grid-cols-[1fr_150px_140px_auto]"><div className="relative"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground" /><Input name="q" defaultValue={query} placeholder="Pretraži dokumente…" className="pl-9" /></div><select name="type" defaultValue={type} className="h-11 rounded-xl border bg-background px-3 text-sm"><option value="">Svi tipovi</option>{Object.entries(documentTypeDefinitions).map(([value, item]) => <option key={value} value={value}>{item.label}</option>)}</select><select name="sort" defaultValue={sort} className="h-11 rounded-xl border bg-background px-3 text-sm"><option value="newest">Najnovije</option><option value="oldest">Najstarije</option><option value="type">Po tipu</option></select><Button variant="outline">Primijeni</Button></form>{recent.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{recent.map((document) => <DocumentCard key={document.id} document={document} />)}</div> : <div className="mt-6 rounded-2xl border border-dashed p-10 text-center"><FilePlus2 className="mx-auto size-9 text-primary" /><h3 className="mt-3 font-semibold">Vaš prostor čeka prvi dokument</h3><p className="mt-1 text-sm text-muted-foreground">Pritisnite Ctrl K ili kreirajte novi dokument.</p></div>}</div>
      <aside className="space-y-5"><section className="rounded-3xl border bg-card p-5"><h2 className="font-semibold">Brze akcije</h2><div className="mt-4 grid gap-2">{quickActions.map(({ label, type: typeValue, Icon }) => <Link key={label} href={`/wizard?type=${typeValue}`} className="flex items-center gap-3 rounded-xl bg-muted/60 p-3 text-sm font-medium transition hover:translate-x-1 hover:bg-muted"><Icon className="size-4 text-primary" />{label}<ArrowRight className="ml-auto size-4 text-muted-foreground" /></Link>)}</div></section><section className="rounded-3xl border bg-card p-5"><h2 className="font-semibold">Najčešće korišteni</h2><div className="mt-3 space-y-1">{frequent.length ? frequent.map((document, index) => <Link key={document.id} href={`/dashboard/documents/${document.id}`} className="flex items-center gap-3 rounded-xl p-2.5 hover:bg-muted"><span className="text-xs font-bold text-muted-foreground">0{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm">{document.title}</span><span className="text-xs text-muted-foreground">{document.open_count}×</span></Link>) : <p className="py-5 text-sm text-muted-foreground">Aktivnost će se pojaviti nakon otvaranja dokumenata.</p>}</div></section>{favorites.length > 0 && <section className="rounded-3xl border bg-card p-5"><div className="flex items-center gap-2"><Star className="size-4 fill-amber-400 text-amber-400" /><h2 className="font-semibold">Omiljeni dokumenti</h2></div><div className="mt-3 space-y-1">{favorites.map((document) => <Link key={document.id} href={`/dashboard/documents/${document.id}`} className="block truncate rounded-lg px-2 py-2 text-sm hover:bg-muted">{document.title}</Link>)}</div></section>}</aside>
    </section>
  </main>;
}
