import type { ProjectSnapshot } from "./types";
const now = new Date().toISOString(); const org = "demo-org"; const projectId = "proj-hidro-centar";
const base = (id: string) => ({ id, organizationId: org, projectId, createdAt: now, updatedAt: now, deletedAt: null });
export const demoProjectSnapshot: ProjectSnapshot = {
  project: { ...base(projectId), code: "GR-2026-014", name: "Sanacija hidroizolacije – Poslovni centar", description: "Sanacija podrumske hidroizolacije i uređenje tehničkih prostorija.", projectType: "sanacija", status: "active", priority: "high", address: "Industrijska 24", city: "Zagreb", postalCode: "10000", country: "Hrvatska", startDate: "2026-07-15", expectedEndDate: "2026-10-30", contractValue: 184000, budget: 156000, currency: "EUR", progressPercent: 42, healthStatus: "at_risk", riskLevel: "high", projectManagerUserId: "demo-user" },
  phases: [
    { ...base("phase-1"), name: "Priprema i zaštita", code: "01", status: "completed", progressPercent: 100, plannedStart: "2026-07-15", plannedEnd: "2026-07-24", budget: 12000, cost: 10920, position: 1 },
    { ...base("phase-2"), name: "Hidroizolacijski radovi", code: "02", status: "in_progress", progressPercent: 55, plannedStart: "2026-07-25", plannedEnd: "2026-09-05", budget: 76000, cost: 43800, position: 2 },
    { ...base("phase-3"), name: "Završni radovi", code: "03", status: "planned", progressPercent: 0, plannedStart: "2026-09-06", plannedEnd: "2026-10-30", budget: 68000, cost: 0, position: 3 },
  ],
  locations: [{ ...base("loc-b1"), name: "Podrum B1", code: "B1", kind: "floor", position: 1, active: true }, { ...base("loc-west"), parentLocationId: "loc-b1", name: "Zapadni zid", code: "B1-Z", kind: "zone", position: 1, active: true }],
  tasks: [
    { ...base("task-1"), phaseId: "phase-2", locationId: "loc-west", title: "Nanijeti drugi sloj hidroizolacije", description: "Kontrola podloge prije nanošenja.", status: "in_progress", priority: "high", taskType: "work", startDate: "2026-07-31", dueDate: "2026-08-03", progressPercent: 60, estimatedHours: 32, actualHours: 18, assignee: "Ekipa Hidro 1", checklist: [{ id: "c1", label: "Podloga suha", completed: true }, { id: "c2", label: "Debljina sloja kontrolirana", completed: false }] },
    { ...base("task-2"), phaseId: "phase-2", title: "Odobrenje detalja prodora", description: "Nadzor treba potvrditi tehničko rješenje.", status: "blocked", priority: "critical", taskType: "approval", startDate: "2026-07-29", dueDate: "2026-08-01", progressPercent: 25, estimatedHours: 8, actualHours: 4, assignee: "Ivan Horvat", checklist: [] },
    { ...base("task-3"), phaseId: "phase-3", title: "Naručiti zaštitne ploče", description: "Isporuka prije početka zatrpavanja.", status: "planned", priority: "normal", taskType: "procurement", startDate: "2026-08-03", dueDate: "2026-08-07", progressPercent: 0, estimatedHours: 2, actualHours: 0, assignee: "Nabava", checklist: [] },
  ],
  workforce: [{ ...base("worker-1"), name: "Marko Kovač", company: "Dokument Gradnja d.o.o.", role: "Poslovođa", crew: "Hidro 1", status: "present", regularHours: 8, overtimeHours: 1, date: "2026-08-01", locationId: "loc-b1" }, { ...base("worker-2"), name: "Amir Hadžić", company: "Hidro Partner d.o.o.", role: "Izolater", crew: "Hidro 1", status: "present", regularHours: 8, overtimeHours: 0, date: "2026-08-01", locationId: "loc-west" }],
  materials: [{ ...base("mat-1"), code: "HI-2K", name: "Dvokomponentna hidroizolacija", category: "Hidroizolacija", unit: "kg", planned: 1200, ordered: 900, delivered: 760, used: 620, damaged: 10, returned: 0, minimum: 150, unitPrice: 4.8, currency: "EUR", status: "partially_delivered", supplier: "Izolacije d.o.o." }, { ...base("mat-2"), code: "MRE-160", name: "Armaturna mrežica 160 g", category: "Armatura", unit: "m²", planned: 850, ordered: 850, delivered: 850, used: 430, damaged: 0, returned: 0, minimum: 100, unitPrice: 1.9, currency: "EUR", status: "delivered", supplier: "Materijal Trade" }],
  equipment: [{ ...base("eq-1"), name: "Airless pumpa", category: "Strojevi", inventoryNumber: "ST-044", status: "in_use", operator: "Amir Hadžić", location: "Podrum B1", usageHours: 46, nextService: "2026-08-14", rentalCost: 80, currency: "EUR" }, { ...base("eq-2"), name: "Industrijski odvlaživač", category: "Oprema", inventoryNumber: "OP-115", status: "reserved", operator: "", location: "Skladište", usageHours: 120, nextService: "2026-09-01", rentalCost: 35, currency: "EUR" }],
  costs: [{ ...base("cost-1"), date: "2026-07-28", name: "Hidroizolacijski materijal", category: "material", supplier: "Izolacije d.o.o.", documentNumber: "URA-884", subtotal: 18240, tax: 4560, total: 22800, currency: "EUR", status: "invoiced", paid: false, phaseId: "phase-2" }, { ...base("cost-2"), date: "2026-07-31", name: "Najam pumpe", category: "equipment", supplier: "Rent Pro", documentNumber: "RN-411", subtotal: 960, tax: 240, total: 1200, currency: "EUR", status: "incurred", paid: false, phaseId: "phase-2" }],
  issues: [{ ...base("issue-1"), title: "Prodor vode kod instalacijskog otvora", description: "Potrebno usuglasiti detalj brtvljenja.", category: "quality", priority: "critical", status: "open", owner: "Ivan Horvat", dueDate: "2026-08-02", costImpact: 1800, scheduleImpactDays: 2, locationId: "loc-west", kind: "issue" }, { ...base("risk-1"), title: "Kašnjenje isporuke zaštitnih ploča", description: "Dobavljač još nije potvrdio termin.", category: "supply", priority: "high", status: "mitigating", owner: "Nabava", dueDate: "2026-08-05", costImpact: 0, scheduleImpactDays: 4, kind: "risk" }],
  meetings: [{ ...base("meet-1"), title: "Tjedna koordinacija", type: "coordination", date: "2026-08-04", time: "09:00", location: "Kontejner gradilišta", organizer: "Ivan Horvat", status: "scheduled", attendees: ["Nadzor", "Izvođač", "Investitor"], decisions: [], actions: ["Potvrditi detalj prodora"] }],
  photos: [{ ...base("photo-1"), title: "Zapadni zid – prvi sloj", description: "Kontrola izvedbe prije drugog sloja", takenAt: "2026-07-31T14:20:00Z", author: "Marko Kovač", category: "progress", locationId: "loc-west", tags: ["hidroizolacija", "prije"] }],
  documents: [{ ...base("doc-link-1"), documentId: "doc-daily", title: "Dnevni izvještaj 31.07.2026.", documentType: "daily_report", status: "completed", updatedAt: now }, { ...base("doc-link-2"), documentId: "doc-po", title: "Narudžbenica zaštitnih ploča", documentType: "purchase_order", status: "draft", updatedAt: now }],
  activity: [{ ...base("act-1"), type: "task_status_changed", message: "Zadatak „Drugi sloj hidroizolacije” pomaknut je u U tijeku.", actor: "Marko Kovač" }, { ...base("act-2"), type: "issue_created", message: "Otvoren je kritičan problem na zapadnom zidu.", actor: "Ivan Horvat" }],
};
