import type{DocumentType}from"@/lib/document-types";import{migratePaperDesign}from"./paper";import type{PaperPreset}from"./types";
export const PAPER_PRESET_STORAGE_KEY="dokument-ai-paper-presets-v1";
export interface PaperPresetStore{version:1;custom:PaperPreset[];defaults:{global?:string;byCompany:Record<string,string>;byDocument:Partial<Record<DocumentType,string>>};recentColors:string[]}
export const emptyPaperPresetStore=():PaperPresetStore=>({version:1,custom:[],defaults:{byCompany:{},byDocument:{}},recentColors:[]});
export function savePaperPreset(store:PaperPresetStore,preset:PaperPreset){if(preset.builtIn)throw new Error("Sistemski preset prvo duplicirajte.");return{...store,custom:[...store.custom.filter(v=>v.id!==preset.id),{...preset,paper:migratePaperDesign(preset.paper),updatedAt:new Date().toISOString()}]}}
export function duplicatePaperPreset(source:PaperPreset,name=`${source.name} kopija`):PaperPreset{const at=new Date().toISOString();return{...structuredClone(source),id:crypto.randomUUID(),name,builtIn:false,createdAt:at,updatedAt:at}}
export function deletePaperPreset(store:PaperPresetStore,id:string){return{...store,custom:store.custom.filter(v=>v.id!==id),defaults:{...store.defaults,global:store.defaults.global===id?undefined:store.defaults.global,byCompany:Object.fromEntries(Object.entries(store.defaults.byCompany).filter(([,v])=>v!==id)),byDocument:Object.fromEntries(Object.entries(store.defaults.byDocument).filter(([,v])=>v!==id))}}}
export const exportPaperPreset=(preset:PaperPreset)=>JSON.stringify(preset,null,2);
export function importPaperPreset(json:string):PaperPreset{const value=JSON.parse(json) as Partial<PaperPreset>;if(!value.name||!value.paper)throw new Error("Paper preset nema obavezna polja.");const at=new Date().toISOString();return{id:crypto.randomUUID(),name:value.name,description:value.description??"Uvezeni paper preset",builtIn:false,paper:migratePaperDesign(value.paper),recommendedFor:value.recommendedFor??["all"],createdAt:at,updatedAt:at}}
export function rememberPaperColor(store:PaperPresetStore,color:string){return{...store,recentColors:[color,...store.recentColors.filter(v=>v!==color)].slice(0,8)}}
