import type { CSSProperties } from "react";import type{DocumentType}from"@/lib/document-types";import type{PaperDesignConfig,PaperPattern,PaperPreset}from"./types";
const now="2026-08-01T00:00:00.000Z";
const pattern=(type:PaperPattern,color="#64748b",opacity=.08):PaperDesignConfig["pattern"]=>({enabled:type!=="none",type,color,opacity,lineWidth:1,spacing:18,size:18,angle:0,position:"page",repeat:true,pages:"all"});
export const defaultPaperDesign=():PaperDesignConfig=>({version:1,presetId:"pure-white",color:{value:"#ffffff",intensity:.04,source:"palette"},pattern:pattern("none"),lines:[],shapes:[],safeZone:true,pageVariants:{firstPageEmphasis:false,middleSimplified:true,lastPageSignatureAccent:false},printSafe:{enabled:true,blackAndWhitePreview:false,inkLevel:"low"}});
const preset=(id:string,name:string,color:string,p:PaperPattern,line?:Partial<PaperDesignConfig["lines"][number]>,shape?:Partial<PaperDesignConfig["shapes"][number]>,recommendedFor:(DocumentType|"all")[]=["all"]):PaperPreset=>{const paper=defaultPaperDesign();paper.presetId=id;paper.color.value=color;paper.pattern=pattern(p,color==="#ffffff"?"#64748b":"#334155",p==="none"?0:.07);if(line)paper.lines=[{id:`${id}-line`,enabled:true,style:"brand",position:"top",color:"#2563eb",thickness:2,length:100,opacity:.75,offset:0,pages:"all",...line}];if(shape)paper.shapes=[{id:`${id}-shape`,enabled:true,type:"circle",x:88,y:5,width:18,height:18,rotation:0,color:"#2563eb",opacity:.06,pages:"first",locked:true,...shape}];return{id,name,description:`${name} profesionalni papirni preset`,builtIn:true,paper,recommendedFor,createdAt:now,updatedAt:now}};
export const paperPresets:PaperPreset[]=[preset("pure-white","Pure White","#ffffff","none"),preset("warm-ivory","Warm Ivory","#fffdf5","paper-texture"),preset("corporate-blue-line","Corporate Blue Line","#fbfdff","none",{position:"left",color:"#2563eb",thickness:4},undefined,["offer","invoice"]),preset("minimal-gray","Minimal Gray","#f8fafc","none",{position:"bottom",color:"#94a3b8",thickness:1}),preset("technical-grid","Technical Grid","#fcfdff","technical-grid",{position:"top",color:"#475569",thickness:1},undefined,["purchase-order","minutes"]),preset("construction-blueprint-light","Construction Blueprint Light","#f8fbff","blueprint",{position:"left",color:"#ea580c",thickness:3},undefined,["daily-report","completed-works-report"]),preset("elegant-gold-accent","Elegant Gold Accent","#fffef9","elegant-curves",{position:"top",color:"#a16207",thickness:2},undefined,["certificate","offer"]),preset("executive-dark-header","Executive Dark Header","#ffffff","none",{position:"top",color:"#0f172a",thickness:12}),preset("soft-green","Soft Green","#f7fdf9","minimal-shapes",undefined,{color:"#16a34a"}),preset("classic-border","Classic Border","#fffefb","page-frame",{position:"frame",color:"#475569",thickness:1},undefined,["contract","work-handover"]),preset("modern-geometry","Modern Geometry","#ffffff","geometry",undefined,{type:"geometric-block",color:"#6366f1"}),preset("clean-letterhead","Clean Letterhead","#ffffff","none",{position:"top",color:"#334155",thickness:2},undefined,["business-letter","request","termination"]),preset("subtle-waves","Subtle Waves","#fbfcff","corporate-waves",undefined,{type:"wave",color:"#2563eb"}),preset("industrial-steel","Industrial Steel","#f8fafc","construction-grid",{position:"left",color:"#475569",thickness:3},undefined,["purchase-order","daily-report"]),preset("custom","Custom","#ffffff","none")];
export const paperPalette=[{name:"Čista bijela",value:"#ffffff"},{name:"Topla bijela",value:"#fffdf7"},{name:"Hladna bijela",value:"#fbfdff"},{name:"Svijetlosiva",value:"#f8fafc"},{name:"Krem",value:"#fffbea"},{name:"Slonovača",value:"#fffef0"},{name:"Vrlo svijetloplava",value:"#f5f9ff"},{name:"Vrlo svijetlozelena",value:"#f5fcf7"},{name:"Vrlo svijetlobež",value:"#fbf8f3"},{name:"Svijetli pijesak",value:"#fcf8ef"}];
export function paperPresetById(id:string){return paperPresets.find(v=>v.id===id)??paperPresets[0]}
export function migratePaperDesign(value:unknown){if(!value||typeof value!=="object")return defaultPaperDesign();const v=value as Partial<PaperDesignConfig>,d=defaultPaperDesign();return{...d,...v,color:{...d.color,...v.color},pattern:{...d.pattern,...v.pattern},pageVariants:{...d.pageVariants,...v.pageVariants},printSafe:{...d.printSafe,...v.printSafe},lines:Array.isArray(v.lines)?v.lines:[],shapes:Array.isArray(v.shapes)?v.shapes:[]}}
const hex=(value:string)=>{const v=value.replace("#","");return v.length===3?v.split("").map(c=>c+c).join(""):v.padEnd(6,"0").slice(0,6)};const rgb=(v:string)=>[0,2,4].map(i=>parseInt(hex(v).slice(i,i+2),16));
export function contrastRatio(a:string,b:string){const lum=(c:string)=>{const values=rgb(c).map(v=>{const s=v/255;return s<=.03928?s/12.92:Math.pow((s+.055)/1.055,2.4)});return .2126*values[0]+.7152*values[1]+.0722*values[2]};const [x,y]=[lum(a),lum(b)].sort((m,n)=>n-m);return(x+.05)/(y+.05)}
export function paperContrast(paper:PaperDesignConfig,textColor:string){const ratio=contrastRatio(paper.color.value,textColor);return{ratio,acceptable:ratio>=4.5,suggestion:contrastRatio(paper.color.value,"#0f172a")>=4.5?"#0f172a":"#ffffff"}}
export function estimateInk(paper:PaperDesignConfig):"low"|"medium"|"high"{const base=paper.color.value.toLowerCase()==="#ffffff"?0:1;const score=base+(paper.pattern.enabled?1:0)+paper.lines.filter(v=>v.enabled&&v.thickness>4).length+paper.shapes.filter(v=>v.enabled&&v.opacity>.12).length;return score>=3?"high":score>=1?"medium":"low"}
function background(patternConfig:PaperDesignConfig["pattern"]){if(!patternConfig.enabled)return"none";const c=patternConfig.color,space=patternConfig.spacing,op=Math.round(patternConfig.opacity*255).toString(16).padStart(2,"0"),color=`${c}${op}`;switch(patternConfig.type){case"horizontal-lines":return`repeating-linear-gradient(0deg,transparent 0,transparent ${space-1}px,${color} ${space}px)`;case"vertical-lines":return`repeating-linear-gradient(90deg,transparent 0,transparent ${space-1}px,${color} ${space}px)`;case"technical-grid":case"construction-grid":case"blueprint":return`linear-gradient(${color} 1px,transparent 1px),linear-gradient(90deg,${color} 1px,transparent 1px)`;case"dot-grid":return`radial-gradient(${color} 1px,transparent 1px)`;case"diagonal-lines":return`repeating-linear-gradient(45deg,transparent 0,transparent ${space-1}px,${color} ${space}px)`;case"corporate-waves":case"elegant-curves":return`radial-gradient(ellipse at 100% 0,${color},transparent 45%)`;case"minimal-shapes":case"geometry":case"corner-details":return`linear-gradient(135deg,${color} 0 8%,transparent 8% 92%,${color} 92%)`;case"side-line":return`linear-gradient(90deg,${color} 0 5px,transparent 5px)`;case"top-line":return`linear-gradient(180deg,${color} 0 5px,transparent 5px)`;case"bottom-line":return`linear-gradient(0deg,${color} 0 5px,transparent 5px)`;case"page-frame":return"none";case"paper-texture":return`radial-gradient(${color} .6px,transparent .8px)`;default:return patternConfig.customCss??"none"}}
export function paperCss(paperInput:PaperDesignConfig):CSSProperties{const paper=migratePaperDesign(paperInput),safe=paper.printSafe.enabled,blackAndWhitePreview=paper.printSafe.blackAndWhitePreview;const image=background(paper.pattern);return{backgroundColor:blackAndWhitePreview?"#ffffff":paper.color.value,backgroundImage:image,backgroundSize:["technical-grid","construction-grid","blueprint","dot-grid","paper-texture"].includes(paper.pattern.type)?`${paper.pattern.spacing}px ${paper.pattern.spacing}px`:undefined,filter:blackAndWhitePreview?"grayscale(1)":undefined,"--paper-pattern-opacity":String(safe?Math.min(paper.pattern.opacity,.06):paper.pattern.opacity)} as CSSProperties}
export function paperSupportsPdf(patternType:PaperPattern){return["none","horizontal-lines","vertical-lines","technical-grid","dot-grid","diagonal-lines","page-frame","side-line","top-line","bottom-line"].includes(patternType)}
