import type { DocumentTheme, DocumentThemeId, FontPairId } from "./types";
import { defaultPaperDesign } from "./paper";
export const fontPairs: Record<FontPairId,{name:string;heading:string;body:string;table:string;small:string}> = {
  "inter-source":{name:"Inter + Source Sans",heading:"Inter",body:"Source Sans 3",table:"Inter",small:"Source Sans 3"}, "montserrat-open":{name:"Montserrat + Open Sans",heading:"Montserrat",body:"Open Sans",table:"Open Sans",small:"Open Sans"}, "lato-merriweather":{name:"Lato + Merriweather",heading:"Lato",body:"Merriweather",table:"Lato",small:"Lato"}, "roboto-slab":{name:"Roboto + Roboto Slab",heading:"Roboto Slab",body:"Roboto",table:"Roboto",small:"Roboto"}, "poppins-noto":{name:"Poppins + Noto Sans",heading:"Poppins",body:"Noto Sans",table:"Noto Sans",small:"Noto Sans"}, "work-source-serif":{name:"Work Sans + Source Serif",heading:"Work Sans",body:"Source Serif 4",table:"Work Sans",small:"Work Sans"}, "ibm-plex":{name:"IBM Plex Sans + IBM Plex Serif",heading:"IBM Plex Sans",body:"IBM Plex Serif",table:"IBM Plex Sans",small:"IBM Plex Sans"},
};
const base=(themeId:DocumentThemeId,fontPairId:FontPairId,colors:[string,string,string,string,string,string,string],overrides:Partial<DocumentTheme["style"]>={}):DocumentTheme["style"]=>{const f=fontPairs[fontPairId],paper=defaultPaperDesign();paper.color.value=colors[6];return{version:2,themeId,fontPairId,accentColor:colors[0],secondaryColor:colors[1],headingColor:colors[2],textColor:colors[3],mutedColor:colors[4],surfaceColor:colors[5],paperColor:colors[6],headingFont:f.heading,bodyFont:f.body,tableFont:f.table,smallFont:f.small,fontSize:10,density:"comfortable",headerVariant:"modern-split",footerVariant:"three-columns",tableVariant:"striped",sectionVariant:"side-accent",totalVariant:"right-box",signatureVariant:"two-columns",page:{size:"A4",orientation:"portrait",margins:{top:14,right:14,bottom:16,left:14},headerHeight:24,footerHeight:14,showPageNumber:true,showPageBorder:false},watermark:{enabled:false,text:"DRAFT",color:"#64748b",opacity:.1,angle:-35},paper,...overrides};};
export const documentThemes:DocumentTheme[]=[
 {id:"corporate-blue",name:"Corporate Blue",description:"Jasni plavi blokovi, strukturirane tablice i moderan poslovni header.",style:base("corporate-blue","inter-source",["#2563eb","#dbeafe","#172554","#172033","#64748b","#eff6ff","#ffffff"])},
 {id:"executive-black",name:"Executive Black",description:"Monokromatski executive raspored s tankim zlatnim naglaskom.",style:base("executive-black","lato-merriweather",["#171717","#d4af37","#0a0a0a","#262626","#737373","#fafafa","#ffffff"],{headerVariant:"minimal",tableVariant:"executive",totalVariant:"executive-summary",sectionVariant:"plain"})},
 {id:"construction-orange",name:"Construction Orange",description:"Tehnički operativni raspored s narančastim statusima i čvrstim linijama.",style:base("construction-orange","roboto-slab",["#ea580c","#ffedd5","#7c2d12","#292524","#78716c","#fff7ed","#ffffff"],{headerVariant:"side-rail",tableVariant:"technical",sectionVariant:"colored-header",density:"compact"})},
 {id:"minimal-gray",name:"Minimal Gray",description:"Tihi sivkasti tonovi, puno reda i minimalni obrubi.",style:base("minimal-gray","inter-source",["#475569","#e2e8f0","#1e293b","#334155","#64748b","#f8fafc","#ffffff"],{headerVariant:"minimal",footerVariant:"line",tableVariant:"minimal",sectionVariant:"plain",totalVariant:"minimal-table"})},
 {id:"modern-green",name:"Modern Green",description:"Svježi zeleni akcent, zaobljeni sažeci i čiste kartice.",style:base("modern-green","poppins-noto",["#15803d","#dcfce7","#14532d","#1f2937","#64748b","#f0fdf4","#ffffff"],{sectionVariant:"card",totalVariant:"summary-card"})},
 {id:"elegant-gold",name:"Elegant Gold",description:"Topla luksuzna tipografija i odmjereni zlatni detalji.",style:base("elegant-gold","work-source-serif",["#a16207","#fef3c7","#713f12","#292524","#78716c","#fffbeb","#fffefb"],{headerVariant:"logo-centered",footerVariant:"branding",tableVariant:"executive",sectionVariant:"plain",totalVariant:"executive-summary",density:"spacious"})},
 {id:"professional-navy",name:"Professional Navy",description:"Stabilan tamnoplavi poslovni identitet i jasan hijerarhijski raspored.",style:base("professional-navy","ibm-plex",["#1e3a8a","#dbeafe","#172554","#172033","#64748b","#eff6ff","#ffffff"],{headerVariant:"classic-business",tableVariant:"solid"})},
 {id:"clean-white",name:"Clean White",description:"Čista bijela stranica, tanke linije i vrlo lagani naglasci.",style:base("clean-white","inter-source",["#0f172a","#f1f5f9","#0f172a","#334155","#64748b","#ffffff","#ffffff"],{headerVariant:"logo-left",footerVariant:"page-number",tableVariant:"minimal",sectionVariant:"plain",totalVariant:"minimal-table"})},
 {id:"technical-steel",name:"Technical Steel",description:"Gusti tehnički prikaz, čelični tonovi i precizne tablice.",style:base("technical-steel","ibm-plex",["#475569","#cbd5e1","#1e293b","#1e293b","#64748b","#f1f5f9","#ffffff"],{headerVariant:"side-rail",footerVariant:"three-columns",tableVariant:"technical",sectionVariant:"table-panel",density:"compact"})},
 {id:"classic-business",name:"Classic Business",description:"Tradicionalni letterhead, serifni sadržaj i uredne poslovne linije.",style:base("classic-business","lato-merriweather",["#334155","#e2e8f0","#1e293b","#292524","#78716c","#f8fafc","#ffffff"],{headerVariant:"classic-business",footerVariant:"contact",tableVariant:"solid",sectionVariant:"bordered"})},
 {id:"premium-dark-header",name:"Premium Dark Header",description:"Veliki tamni header, visoki kontrast i premium sažeci.",style:base("premium-dark-header","montserrat-open",["#0f172a","#334155","#0f172a","#1e293b","#64748b","#f8fafc","#ffffff"],{headerVariant:"dark",footerVariant:"branding",tableVariant:"executive",sectionVariant:"card",totalVariant:"full-bar"})},
 {id:"soft-modern",name:"Soft Modern",description:"Meki indigo tonovi, prozračne kartice i prijateljski moderan dojam.",style:base("soft-modern","poppins-noto",["#6366f1","#e0e7ff","#312e81","#312e81","#7c83a0","#f5f3ff","#ffffff"],{headerVariant:"modern-split",footerVariant:"line",tableVariant:"striped",sectionVariant:"shaded",totalVariant:"summary-card",density:"spacious"})},
];
export const documentThemeById=(id:DocumentThemeId)=>documentThemes.find(t=>t.id===id)??documentThemes[0];
