-- Dokument AI multi-tenant SaaS baseline. Apply with `supabase db push` after review.
create extension if not exists pgcrypto;
create type public.organization_role as enum ('owner','admin','manager','editor','viewer','accountant');
create type public.member_status as enum ('active','invited','suspended');

alter table public.profiles add column if not exists first_name text not null default '', add column if not exists last_name text not null default '', add column if not exists display_name text not null default '', add column if not exists email text not null default '', add column if not exists phone text not null default '', add column if not exists country text not null default '', add column if not exists city text not null default '', add column if not exists language text not null default 'hr', add column if not exists timezone text not null default 'Europe/Zagreb', add column if not exists preferred_currency text not null default 'EUR', add column if not exists date_format text not null default 'dd.MM.yyyy.', add column if not exists number_format text not null default 'hr-HR', add column if not exists avatar_path text, add column if not exists current_organization_id uuid, add column if not exists onboarding_completed boolean not null default false, add column if not exists deleted_at timestamptz;

create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, logo_path text, country text not null default '', default_language text not null default 'hr', default_currency text not null default 'EUR', plan text not null default 'free', created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
alter table public.profiles add constraint profiles_current_organization_fk foreign key (current_organization_id) references public.organizations(id) on delete set null;
create table public.organization_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role public.organization_role not null default 'viewer', status public.member_status not null default 'active', joined_at timestamptz, created_at timestamptz not null default now(), unique(organization_id,user_id));
create table public.organization_invitations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, email text not null, role public.organization_role not null, status text not null default 'pending' check(status in('pending','accepted','declined','expired','revoked')), token_hash text not null unique, invited_by uuid not null references auth.users(id), expires_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create or replace function public.is_org_member(org uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.organization_members m where m.organization_id=org and m.user_id=(select auth.uid()) and m.status='active') $$;
create or replace function public.has_org_role(org uuid, roles public.organization_role[]) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.organization_members m where m.organization_id=org and m.user_id=(select auth.uid()) and m.status='active' and m.role=any(roles)) $$;
revoke all on function public.is_org_member(uuid) from public; revoke all on function public.has_org_role(uuid,public.organization_role[]) from public; grant execute on function public.is_org_member(uuid),public.has_org_role(uuid,public.organization_role[]) to authenticated;

create table public.companies (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, legal_name text not null default '', address text not null default '', city text not null default '', postal_code text not null default '', country text not null default '', tax_number text not null default '', vat_number text not null default '', registration_number text not null default '', phone text not null default '', email text not null default '', website text not null default '', responsible_person text not null default '', default_language text not null default 'hr', default_currency text not null default 'EUR', active boolean not null default true, is_default boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.company_bank_accounts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid not null references public.companies(id) on delete cascade, iban text not null, swift text, bank_name text, currency text not null default 'EUR', is_default boolean not null default false, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.company_assets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid not null references public.companies(id) on delete cascade, kind text not null check(kind in('logo','signature','stamp')), name text not null, storage_path text not null, mime_type text not null, is_default boolean not null default false, created_at timestamptz not null default now(), deleted_at timestamptz);

create table public.contacts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), type text not null default 'customer', company_name text not null default '', first_name text not null default '', last_name text not null default '', tax_number text not null default '', vat_number text not null default '', email text not null default '', phone text not null default '', website text not null default '', active boolean not null default true, is_archived boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.contact_people (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), contact_id uuid not null references public.contacts(id) on delete cascade, first_name text not null, last_name text not null default '', role text, email text, phone text, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.contact_addresses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), contact_id uuid not null references public.contacts(id) on delete cascade, kind text not null default 'main', address text not null, city text, postal_code text, country text, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.contact_bank_accounts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), contact_id uuid not null references public.contacts(id) on delete cascade, iban text not null, swift text, bank_name text, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.contact_tags (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, color text, unique(organization_id,name));
create table public.contact_tag_links (organization_id uuid not null references public.organizations(id), contact_id uuid not null references public.contacts(id) on delete cascade, tag_id uuid not null references public.contact_tags(id) on delete cascade, primary key(contact_id,tag_id));
create table public.contact_notes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), contact_id uuid not null references public.contacts(id) on delete cascade, author_user_id uuid not null references auth.users(id), note text not null, created_at timestamptz not null default now(), deleted_at timestamptz);

create table public.projects (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid references public.companies(id), name text not null, code text not null default '', description text not null default '', address text not null default '', city text not null default '', country text not null default '', client_contact_id uuid references public.contacts(id), investor_contact_id uuid references public.contacts(id), status text not null default 'draft', start_date date, expected_end_date date, actual_end_date date, budget_minor bigint, currency text not null default 'EUR', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.project_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id) on delete cascade, user_id uuid not null references auth.users(id), role text not null, created_at timestamptz not null default now(), unique(project_id,user_id));
create table public.project_phases (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id) on delete cascade, name text not null, position integer not null default 0, status text not null default 'planned', created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.project_locations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id) on delete cascade, parent_id uuid references public.project_locations(id), name text not null, kind text, position integer not null default 0, created_at timestamptz not null default now(), deleted_at timestamptz);

alter table public.documents rename column user_id to owner_user_id; alter table public.documents rename column type to document_type; alter table public.documents rename column content to rendered_content;
alter table public.documents add column if not exists organization_id uuid references public.organizations(id), add column if not exists company_id uuid references public.companies(id), add column if not exists contact_id uuid references public.contacts(id), add column if not exists project_id uuid references public.projects(id), add column if not exists source_document_id uuid references public.documents(id), add column if not exists document_category text not null default 'administration', add column if not exists document_number text not null default '', add column if not exists status text not null default 'draft', add column if not exists language text not null default 'hr', add column if not exists currency text not null default 'EUR', add column if not exists template_id uuid, add column if not exists visibility_profile_id uuid, add column if not exists form_data jsonb not null default '{}'::jsonb, add column if not exists subtotal_minor bigint not null default 0, add column if not exists tax_minor bigint not null default 0, add column if not exists total_minor bigint not null default 0, add column if not exists version integer not null default 1, add column if not exists is_locked boolean not null default false, add column if not exists is_archived boolean not null default false, add column if not exists deleted_at timestamptz;
alter table public.documents drop constraint if exists documents_type_check;
create table public.document_versions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), document_id uuid not null references public.documents(id) on delete cascade, version_number integer not null, snapshot jsonb not null, created_by uuid not null references auth.users(id), reason text, important boolean not null default false, created_at timestamptz not null default now(), unique(document_id,version_number));
create table public.document_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), document_id uuid not null references public.documents(id) on delete cascade, group_id uuid, position integer not null default 0, code text, name text not null, description text, quantity_decimal numeric(20,6) not null default 0, unit text, unit_price_minor bigint not null default 0, discount_percent numeric(8,4) not null default 0, tax_percent numeric(8,4) not null default 0, subtotal_minor bigint not null default 0, tax_minor bigint not null default 0, total_minor bigint not null default 0, is_visible boolean not null default true, include_in_calculation boolean not null default true, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.document_groups (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), document_id uuid not null references public.documents(id) on delete cascade, name text not null, position integer not null default 0, is_visible boolean not null default true, include_in_calculation boolean not null default true, settings jsonb not null default '{}'::jsonb, metadata jsonb not null default '{}'::jsonb, deleted_at timestamptz);
alter table public.document_items add constraint document_items_group_fk foreign key(group_id) references public.document_groups(id) on delete set null;
create table public.document_sections (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), document_id uuid not null references public.documents(id) on delete cascade, section_key text not null, position integer not null default 0, is_visible boolean not null default true, include_in_calculation boolean not null default true, settings jsonb not null default '{}'::jsonb, metadata jsonb not null default '{}'::jsonb, deleted_at timestamptz);
create table public.document_text_blocks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), document_id uuid not null references public.documents(id) on delete cascade, section_id uuid references public.document_sections(id), position integer not null default 0, title text, content text not null default '', is_visible boolean not null default true, deleted_at timestamptz);

create table public.visibility_profiles (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), owner_user_id uuid references auth.users(id), company_id uuid references public.companies(id), document_type text, name text not null, scope text not null default 'user', is_default boolean not null default false, settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.templates (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), owner_user_id uuid references auth.users(id), name text not null, scope text not null check(scope in('system','user','organization')), document_types text[] not null default array['all'], current_version integer not null default 1, is_default boolean not null default false, is_archived boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.template_versions (id uuid primary key default gen_random_uuid(), template_id uuid not null references public.templates(id) on delete cascade, version_number integer not null, definition jsonb not null, created_by uuid references auth.users(id), created_at timestamptz not null default now(), unique(template_id,version_number));
create table public.template_assignments (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), owner_user_id uuid references auth.users(id), company_id uuid references public.companies(id), document_type text not null, template_id uuid not null references public.templates(id), created_at timestamptz not null default now());

create table public.document_attachments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), document_id uuid not null references public.documents(id), uploaded_by uuid not null references auth.users(id), file_name text not null, storage_path text not null, mime_type text not null, file_size bigint not null check(file_size between 1 and 52428800), category text, description text, is_visible boolean not null default true, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.document_exports (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), document_id uuid not null references public.documents(id), format text not null check(format in('pdf','docx')), storage_path text not null, generated_by uuid not null references auth.users(id), document_version integer not null, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), actor_user_id uuid references auth.users(id), action text not null, entity_type text not null, entity_id uuid, safe_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.analytics_events (event_id uuid primary key, organization_id uuid references public.organizations(id), anonymous_session_id uuid not null, user_id uuid references auth.users(id), event_name text not null, document_type text not null, document_category text not null, template_id text, language text not null, device_type text not null, current_step integer, total_steps integer, duration_seconds integer, created_at timestamptz not null default now());
create table public.subscriptions (id uuid primary key default gen_random_uuid(), organization_id uuid not null unique references public.organizations(id), provider text not null default 'stripe', provider_customer_id text, provider_subscription_id text, plan text not null default 'free', status text not null default 'inactive', current_period_end timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.usage_counters (organization_id uuid not null references public.organizations(id), period_start date not null, documents_created integer not null default 0, exports_created integer not null default 0, storage_bytes bigint not null default 0, primary key(organization_id,period_start));

create index documents_org_updated_idx on public.documents(organization_id,updated_at desc) where deleted_at is null; create index contacts_org_search_idx on public.contacts(organization_id,company_name,last_name) where deleted_at is null; create index projects_org_status_idx on public.projects(organization_id,status) where deleted_at is null; create index audit_logs_org_created_idx on public.audit_logs(organization_id,created_at desc);

do $$ declare t text; begin foreach t in array array['organizations','organization_members','organization_invitations','companies','company_bank_accounts','company_assets','contacts','contact_people','contact_addresses','contact_bank_accounts','contact_tags','contact_tag_links','contact_notes','projects','project_members','project_phases','project_locations','documents','document_versions','document_items','document_groups','document_sections','document_text_blocks','visibility_profiles','templates','template_versions','template_assignments','document_attachments','document_exports','audit_logs','analytics_events','subscriptions','usage_counters'] loop execute format('alter table public.%I enable row level security',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); end loop; end $$;
create policy organizations_select on public.organizations for select to authenticated using(public.is_org_member(id)); create policy organizations_insert on public.organizations for insert to authenticated with check(created_by=(select auth.uid())); create policy organizations_update on public.organizations for update to authenticated using(public.has_org_role(id,array['owner','admin']::public.organization_role[])); create policy organizations_delete on public.organizations for delete to authenticated using(public.has_org_role(id,array['owner']::public.organization_role[]));
create policy members_select on public.organization_members for select to authenticated using(public.is_org_member(organization_id)); create policy members_write on public.organization_members for all to authenticated using(public.has_org_role(organization_id,array['owner','admin']::public.organization_role[])) with check(public.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
do $$ declare t text; begin foreach t in array array['organization_invitations','companies','company_bank_accounts','company_assets','contacts','contact_people','contact_addresses','contact_bank_accounts','contact_tags','contact_tag_links','contact_notes','projects','project_members','project_phases','project_locations','document_versions','document_items','document_groups','document_sections','document_text_blocks','document_attachments','document_exports'] loop execute format('create policy %I_select on public.%I for select to authenticated using(public.is_org_member(organization_id))',t,t); execute format('create policy %I_write on public.%I for all to authenticated using(public.has_org_role(organization_id,array[''owner'',''admin'',''manager'',''editor'',''accountant'']::public.organization_role[])) with check(public.has_org_role(organization_id,array[''owner'',''admin'',''manager'',''editor'',''accountant'']::public.organization_role[]))',t,t); end loop; end $$;
create policy documents_org_select on public.documents for select to authenticated using(public.is_org_member(organization_id)); create policy documents_org_write on public.documents for all to authenticated using(public.has_org_role(organization_id,array['owner','admin','manager','editor','accountant']::public.organization_role[])) with check(owner_user_id=(select auth.uid()) and public.has_org_role(organization_id,array['owner','admin','manager','editor','accountant']::public.organization_role[]));
create policy visibility_select on public.visibility_profiles for select to authenticated using((owner_user_id=(select auth.uid())) or public.is_org_member(organization_id)); create policy visibility_write on public.visibility_profiles for all to authenticated using(owner_user_id=(select auth.uid()) or public.has_org_role(organization_id,array['owner','admin']::public.organization_role[])) with check(owner_user_id=(select auth.uid()) or public.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
create policy templates_select on public.templates for select to authenticated using(scope='system' or owner_user_id=(select auth.uid()) or public.is_org_member(organization_id)); create policy templates_write on public.templates for all to authenticated using(scope<>'system' and (owner_user_id=(select auth.uid()) or public.has_org_role(organization_id,array['owner','admin']::public.organization_role[]))) with check(scope<>'system' and (owner_user_id=(select auth.uid()) or public.has_org_role(organization_id,array['owner','admin']::public.organization_role[])));
create policy template_versions_select on public.template_versions for select to authenticated using(exists(select 1 from public.templates t where t.id=template_id and (t.scope='system' or t.owner_user_id=(select auth.uid()) or public.is_org_member(t.organization_id)))); create policy template_versions_write on public.template_versions for insert to authenticated with check(exists(select 1 from public.templates t where t.id=template_id and t.scope<>'system' and (t.owner_user_id=(select auth.uid()) or public.has_org_role(t.organization_id,array['owner','admin']::public.organization_role[]))));
create policy assignments_select on public.template_assignments for select to authenticated using(owner_user_id=(select auth.uid()) or public.is_org_member(organization_id)); create policy assignments_write on public.template_assignments for all to authenticated using(owner_user_id=(select auth.uid()) or public.has_org_role(organization_id,array['owner','admin']::public.organization_role[])) with check(owner_user_id=(select auth.uid()) or public.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
create policy audit_select on public.audit_logs for select to authenticated using(public.has_org_role(organization_id,array['owner','admin']::public.organization_role[])); create policy audit_insert on public.audit_logs for insert to authenticated with check(actor_user_id=(select auth.uid()) and public.is_org_member(organization_id));
create policy analytics_insert on public.analytics_events for insert to authenticated with check((user_id=(select auth.uid()) or user_id is null) and (organization_id is null or public.is_org_member(organization_id))); create policy analytics_select on public.analytics_events for select to authenticated using(public.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
create policy subscriptions_select on public.subscriptions for select to authenticated using(public.is_org_member(organization_id)); create policy subscriptions_owner on public.subscriptions for all to authenticated using(public.has_org_role(organization_id,array['owner']::public.organization_role[])) with check(public.has_org_role(organization_id,array['owner']::public.organization_role[]));
create policy usage_select on public.usage_counters for select to authenticated using(public.is_org_member(organization_id));

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,full_name,first_name,last_name,display_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.raw_user_meta_data->>'first_name',''),coalesce(new.raw_user_meta_data->>'last_name',''),coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.email,'')) on conflict(id) do update set email=excluded.email; return new; end $$;
create or replace function public.add_organization_owner() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.organization_members(organization_id,user_id,role,status,joined_at) values(new.id,new.created_by,'owner','active',now()); return new; end $$;
drop trigger if exists organization_add_owner on public.organizations; create trigger organization_add_owner after insert on public.organizations for each row execute function public.add_organization_owner();

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('private-documents','private-documents',false,52428800,array['image/png','image/jpeg','image/webp','image/svg+xml','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document']) on conflict(id) do update set public=false;
create policy storage_org_select on storage.objects for select to authenticated using(bucket_id='private-documents' and public.is_org_member(((storage.foldername(name))[1])::uuid)); create policy storage_org_insert on storage.objects for insert to authenticated with check(bucket_id='private-documents' and public.has_org_role(((storage.foldername(name))[1])::uuid,array['owner','admin','manager','editor','accountant']::public.organization_role[])); create policy storage_org_update on storage.objects for update to authenticated using(bucket_id='private-documents' and public.has_org_role(((storage.foldername(name))[1])::uuid,array['owner','admin','manager','editor','accountant']::public.organization_role[])); create policy storage_org_delete on storage.objects for delete to authenticated using(bucket_id='private-documents' and public.has_org_role(((storage.foldername(name))[1])::uuid,array['owner','admin']::public.organization_role[]));
