-- Billing projection. Stripe remains the source of truth for provider-controlled subscriptions.
create table public.plans (id text primary key, name text not null, description text not null, active boolean not null default true, trial_days integer not null default 0, recommended boolean not null default false, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.plan_prices (id uuid primary key default gen_random_uuid(), plan_id text not null references public.plans(id), currency text not null, billing_interval text not null check(billing_interval in('month','year')), amount_minor bigint not null check(amount_minor>=0), stripe_price_id text, active boolean not null default true, unique(plan_id,currency,billing_interval));
create table public.plan_features (plan_id text not null references public.plans(id) on delete cascade, feature_key text not null, enabled boolean not null default false, primary key(plan_id,feature_key));
create table public.plan_limits (plan_id text not null references public.plans(id) on delete cascade, limit_key text not null, limit_value bigint not null check(limit_value>=0), primary key(plan_id,limit_key));

alter table public.subscriptions add column if not exists plan_id text references public.plans(id), add column if not exists billing_interval text not null default 'month', add column if not exists current_period_start timestamptz, add column if not exists trial_start timestamptz, add column if not exists trial_end timestamptz, add column if not exists cancel_at_period_end boolean not null default false, add column if not exists canceled_at timestamptz, add column if not exists ended_at timestamptz, add column if not exists seats integer not null default 1, add column if not exists grace_period_end timestamptz, add column if not exists grant_source text, add column if not exists safe_metadata jsonb not null default '{}'::jsonb;
update public.subscriptions set plan_id=coalesce(plan_id,plan,'free');

create table public.subscription_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), subscription_id uuid references public.subscriptions(id), event_type text not null, from_plan text, to_plan text, safe_metadata jsonb not null default '{}'::jsonb, actor_user_id uuid references auth.users(id), created_at timestamptz not null default now());
create table public.billing_customers (id uuid primary key default gen_random_uuid(), organization_id uuid not null unique references public.organizations(id), stripe_customer_id text unique, billing_email text, billing_name text, billing_address jsonb not null default '{}'::jsonb, tax_id text, vat_id text, country text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.billing_invoices (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), stripe_invoice_id text not null unique, stripe_customer_id text, invoice_number text, period_start timestamptz, period_end timestamptz, amount_due_minor bigint not null default 0, amount_paid_minor bigint not null default 0, currency text not null default 'EUR', status text not null, hosted_invoice_url text, invoice_pdf_url text, payment_brand text, payment_last4 text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.billing_payments (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), stripe_payment_intent_id text unique, stripe_charge_id text, invoice_id uuid references public.billing_invoices(id), amount_minor bigint not null default 0, refunded_minor bigint not null default 0, currency text not null default 'EUR', status text not null, dispute_status text, safe_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.billing_coupons (id uuid primary key default gen_random_uuid(), code text not null unique, stripe_coupon_id text, stripe_promotion_code_id text, discount_type text not null check(discount_type in('percent','fixed')), percent_off numeric(5,2), amount_off_minor bigint, currency text, duration text not null check(duration in('once','repeating','forever')), duration_months integer, plan_ids text[] not null default '{}', interval text, minimum_amount_minor bigint, starts_at timestamptz, ends_at timestamptz, max_redemptions integer, per_user_once boolean not null default true, per_organization_once boolean not null default true, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.billing_coupon_redemptions (id uuid primary key default gen_random_uuid(), coupon_id uuid not null references public.billing_coupons(id), organization_id uuid not null references public.organizations(id), user_id uuid not null references auth.users(id), subscription_id uuid references public.subscriptions(id), amount_discounted_minor bigint not null default 0, redeemed_at timestamptz not null default now());
create table public.usage_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), user_id uuid references auth.users(id), usage_key text not null, amount bigint not null, idempotency_key text not null, resource_type text, resource_id uuid, safe_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(organization_id,idempotency_key));
alter table public.usage_counters add column if not exists usage_key text not null default 'documents', add column if not exists usage_value bigint not null default 0, add column if not exists updated_at timestamptz not null default now();
alter table public.usage_counters drop constraint if exists usage_counters_pkey;
alter table public.usage_counters add primary key(organization_id,period_start,usage_key);
create table public.stripe_webhook_events (stripe_event_id text primary key, event_type text not null, status text not null, processed_at timestamptz, error_message text, safe_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.billing_notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), user_id uuid references auth.users(id), event_type text not null, title text not null, message text not null, action_url text, read_at timestamptz, archived_at timestamptz, created_at timestamptz not null default now());
create table public.billing_email_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), user_id uuid references auth.users(id), event_type text not null, status text not null default 'pending', safe_metadata jsonb not null default '{}'::jsonb, sent_at timestamptz, created_at timestamptz not null default now());

insert into public.plans(id,name,description,trial_days,recommended,sort_order) values ('free','Free','Osnovna izrada dokumenata',0,false,0),('basic','Basic','Za samostalne profesionalce',7,false,1),('pro','Pro','Za tvrtke koje svakodnevno rade s dokumentima',14,true,2),('business','Business','Za timove i organizacije',14,false,3) on conflict(id) do update set name=excluded.name,description=excluded.description,trial_days=excluded.trial_days,recommended=excluded.recommended,sort_order=excluded.sort_order;
insert into public.plan_prices(plan_id,currency,billing_interval,amount_minor,stripe_price_id) values ('free','EUR','month',0,null),('free','EUR','year',0,null),('basic','EUR','month',1200,null),('basic','EUR','year',12000,null),('pro','EUR','month',2900,null),('pro','EUR','year',29000,null),('business','EUR','month',7900,null),('business','EUR','year',79000,null) on conflict(plan_id,currency,billing_interval) do update set amount_minor=excluded.amount_minor;

create or replace function public.ensure_free_subscription() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.subscriptions(organization_id,provider,plan,status,plan_id,billing_interval,current_period_start,current_period_end) values(new.id,'manual','free','free','free','month',now(),now()+interval '100 years') on conflict(organization_id) do nothing; return new; end $$;
drop trigger if exists organization_free_subscription on public.organizations; create trigger organization_free_subscription after insert on public.organizations for each row execute function public.ensure_free_subscription();

do $$ declare t text; begin foreach t in array array['plans','plan_prices','plan_features','plan_limits','subscription_events','billing_customers','billing_invoices','billing_payments','billing_coupons','billing_coupon_redemptions','usage_events','stripe_webhook_events','billing_notifications','billing_email_events'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
grant select on public.plans,public.plan_prices,public.plan_features,public.plan_limits to anon,authenticated;
grant select,insert,update,delete on public.subscription_events,public.billing_customers,public.billing_invoices,public.billing_payments,public.billing_coupon_redemptions,public.usage_events,public.billing_notifications,public.billing_email_events to authenticated;
create policy plans_public_read on public.plans for select using(active); create policy prices_public_read on public.plan_prices for select using(active); create policy features_public_read on public.plan_features for select using(true); create policy limits_public_read on public.plan_limits for select using(true);
create policy billing_customers_read on public.billing_customers for select to authenticated using(public.is_org_member(organization_id)); create policy billing_customers_manage on public.billing_customers for all to authenticated using(public.has_org_role(organization_id,array['owner','admin']::public.organization_role[])) with check(public.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
do $$ declare t text; begin foreach t in array array['subscription_events','billing_invoices','billing_payments','billing_coupon_redemptions','usage_events','billing_notifications','billing_email_events'] loop execute format('create policy %I_read on public.%I for select to authenticated using(public.is_org_member(organization_id))',t,t); end loop; end $$;
create policy notifications_update on public.billing_notifications for update to authenticated using(user_id=(select auth.uid()) or public.has_org_role(organization_id,array['owner','admin']::public.organization_role[]));
create policy coupons_admin_read on public.billing_coupons for select to authenticated using(exists(select 1 from public.organization_members m where m.user_id=(select auth.uid()) and m.role in('owner','admin')));
-- stripe_webhook_events is intentionally service-role only; no authenticated policy.
