-- Platform administration is separate from organization RBAC.
create table public.platform_admin_roles (role_key text primary key, name text not null, description text not null, system_role boolean not null default true, created_at timestamptz not null default now());
create table public.platform_admin_permissions (permission_key text primary key, description text not null, created_at timestamptz not null default now());
create table public.platform_admin_role_permissions (role_key text not null references public.platform_admin_roles(role_key) on delete cascade, permission_key text not null references public.platform_admin_permissions(permission_key) on delete cascade, primary key(role_key,permission_key));
create table public.platform_admins (user_id uuid primary key references auth.users(id) on delete cascade, role text not null references public.platform_admin_roles(role_key), display_name text not null default '', status text not null default 'active' check(status in('active','suspended','revoked')), granted_by uuid references auth.users(id), granted_at timestamptz not null default now(), last_admin_activity_at timestamptz, revoked_at timestamptz);

insert into public.platform_admin_roles(role_key,name,description) values ('super_admin','Super Admin','Sve platform ovlasti'),('platform_admin','Platform Admin','Operativno upravljanje platformom'),('support_agent','Support Agent','Podrška i sigurni metapodaci'),('billing_admin','Billing Admin','Pretplate i billing'),('content_admin','Content Admin','CMS, help i predlošci'),('analyst','Analyst','Agregirana analitika'),('readonly_admin','Readonly Admin','Samo pregled') on conflict do nothing;
insert into public.platform_admin_permissions(permission_key,description) values ('admins:manage','Admin korisnici'),('users:read','Pregled korisnika'),('users:manage','Upravljanje statusom korisnika'),('organizations:read','Pregled organizacija'),('organizations:manage','Upravljanje organizacijama'),('billing:read','Pregled billinga'),('billing:manage','Billing operacije'),('content:read','Pregled sadržaja'),('content:manage','Objava sadržaja'),('support:read','Pregled podrške'),('support:manage','Rad na tiketima'),('analytics:read','Agregirana analitika'),('ai:read','AI agregati'),('ai:manage','AI postavke'),('security:read','Security događaji'),('security:manage','Security akcije'),('audit:read','Audit pregled'),('system:manage','Sistemske postavke'),('exports:create','Sigurni admin izvozi') on conflict do nothing;
insert into public.platform_admin_role_permissions select 'super_admin',permission_key from public.platform_admin_permissions on conflict do nothing;
insert into public.platform_admin_role_permissions values ('support_agent','users:read'),('support_agent','organizations:read'),('support_agent','support:read'),('support_agent','support:manage'),('support_agent','audit:read'),('billing_admin','users:read'),('billing_admin','organizations:read'),('billing_admin','billing:read'),('billing_admin','billing:manage'),('billing_admin','audit:read'),('content_admin','content:read'),('content_admin','content:manage'),('content_admin','support:read'),('analyst','analytics:read'),('analyst','billing:read'),('analyst','ai:read'),('readonly_admin','users:read'),('readonly_admin','organizations:read'),('readonly_admin','billing:read'),('readonly_admin','content:read'),('readonly_admin','support:read'),('readonly_admin','analytics:read'),('readonly_admin','ai:read'),('readonly_admin','security:read'),('readonly_admin','audit:read') on conflict do nothing;
insert into public.platform_admin_role_permissions select 'platform_admin',permission_key from public.platform_admin_permissions where permission_key not in('admins:manage','security:manage','system:manage') on conflict do nothing;

create or replace function public.has_platform_permission(required_permission text) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.platform_admins a join public.platform_admin_role_permissions rp on rp.role_key=a.role where a.user_id=(select auth.uid()) and a.status='active' and rp.permission_key=required_permission) $$;
revoke all on function public.has_platform_permission(text) from public; grant execute on function public.has_platform_permission(text) to authenticated;

alter table public.profiles add column if not exists account_status text not null default 'active', add column if not exists suspended_at timestamptz, add column if not exists suspended_reason text, add column if not exists onboarding_reset_at timestamptz;
create table public.admin_user_notes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), author_admin_id uuid not null references auth.users(id), note text not null check(length(note)<=4000), created_at timestamptz not null default now());
create table public.admin_user_tags (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), tag text not null, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), unique(user_id,tag));

create table public.support_tickets (id uuid primary key default gen_random_uuid(), ticket_number bigint generated always as identity unique, user_id uuid not null references auth.users(id), organization_id uuid references public.organizations(id), subject text not null, category text not null, priority text not null default 'normal', status text not null default 'new', assigned_to uuid references auth.users(id), satisfaction_score smallint check(satisfaction_score between 1 and 5), sla_due_at timestamptz, merged_into_id uuid references public.support_tickets(id), billing_reference_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), closed_at timestamptz, deleted_at timestamptz);
create table public.support_ticket_messages (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.support_tickets(id) on delete cascade, author_user_id uuid not null references auth.users(id), body text not null, internal boolean not null default false, created_at timestamptz not null default now(), edited_at timestamptz);
create table public.support_ticket_attachments (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.support_tickets(id) on delete cascade, message_id uuid references public.support_ticket_messages(id), uploaded_by uuid not null references auth.users(id), storage_path text not null, file_name text not null, mime_type text not null, file_size bigint not null check(file_size between 1 and 26214400), created_at timestamptz not null default now());
create table public.support_ticket_events (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.support_tickets(id) on delete cascade, actor_user_id uuid references auth.users(id), event_type text not null, safe_metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.support_macros (id uuid primary key default gen_random_uuid(), name text not null, body text not null, category text, active boolean not null default true, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.support_tags (id uuid primary key default gen_random_uuid(), name text not null unique, color text, created_at timestamptz not null default now());
create table public.support_ticket_tag_links (ticket_id uuid references public.support_tickets(id) on delete cascade, tag_id uuid references public.support_tags(id) on delete cascade, primary key(ticket_id,tag_id));
create table public.support_document_access (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.support_tickets(id), document_id uuid not null references public.documents(id), granted_by uuid not null references auth.users(id), granted_to uuid references auth.users(id), allow_download boolean not null default false, expires_at timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now());
create table public.support_access_events (id uuid primary key default gen_random_uuid(), access_id uuid not null references public.support_document_access(id), actor_user_id uuid not null references auth.users(id), action text not null, created_at timestamptz not null default now());

create table public.bugs (id uuid primary key default gen_random_uuid(), reporter_user_id uuid references auth.users(id), organization_id uuid references public.organizations(id), title text not null, description text not null, reproduction_steps text, expected_behavior text, actual_behavior text, severity text not null default 'normal', status text not null default 'new', browser text, device text, os text, app_version text, route text, error_id text, safe_document_metadata jsonb not null default '{}', assigned_to uuid references auth.users(id), duplicate_of uuid references public.bugs(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.bug_comments (id uuid primary key default gen_random_uuid(), bug_id uuid not null references public.bugs(id) on delete cascade, author_user_id uuid not null references auth.users(id), body text not null, internal boolean not null default false, created_at timestamptz not null default now());
create table public.feature_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), organization_id uuid references public.organizations(id), title text not null, description text not null, category text, status text not null default 'submitted', planned_version text, platform_response text, public boolean not null default false, merged_into_id uuid references public.feature_requests(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.feature_votes (feature_request_id uuid references public.feature_requests(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(feature_request_id,user_id));
create table public.roadmap_items (id uuid primary key default gen_random_uuid(), title text not null, description text, column_key text not null, status text not null default 'draft', target_release text, public boolean not null default false, position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz);

create table public.help_categories (id uuid primary key default gen_random_uuid(), parent_id uuid references public.help_categories(id), slug text not null, locale text not null default 'hr', title text not null, description text, position integer not null default 0, unique(slug,locale));
create table public.help_articles (id uuid primary key default gen_random_uuid(), category_id uuid references public.help_categories(id), slug text not null, locale text not null default 'hr', title text not null, summary text, body text not null default '', seo_title text, seo_description text, status text not null default 'draft', version integer not null default 1, published_at timestamptz, scheduled_at timestamptz, author_id uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, unique(slug,locale,version));
create table public.help_article_feedback (article_id uuid references public.help_articles(id) on delete cascade, user_id uuid references auth.users(id), helpful boolean not null, created_at timestamptz not null default now(), primary key(article_id,user_id));
create table public.cms_pages (id uuid primary key default gen_random_uuid(), slug text not null, locale text not null default 'hr', title text not null, status text not null default 'draft', version integer not null default 1, scheduled_at timestamptz, published_at timestamptz, author_id uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, unique(slug,locale,version));
create table public.cms_blocks (id uuid primary key default gen_random_uuid(), page_id uuid not null references public.cms_pages(id) on delete cascade, block_key text not null, block_type text not null, content jsonb not null default '{}', position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.email_templates (id uuid primary key default gen_random_uuid(), template_key text not null, locale text not null default 'hr', subject text not null, preview_text text, html_body text not null, plain_text_body text not null, status text not null default 'draft', version integer not null default 1, author_id uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(template_key,locale,version));
create table public.notification_campaigns (id uuid primary key default gen_random_uuid(), title text not null, message text not null, notification_type text not null, cta_label text, cta_url text, target jsonb not null default '{}', starts_at timestamptz, ends_at timestamptz, dismissible boolean not null default true, priority integer not null default 0, status text not null default 'draft', created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.release_notes (id uuid primary key default gen_random_uuid(), version text not null unique, title text not null, summary text not null, features jsonb not null default '[]', improvements jsonb not null default '[]', fixes jsonb not null default '[]', known_issues jsonb not null default '[]', public boolean not null default false, published_at timestamptz, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.system_incidents (id uuid primary key default gen_random_uuid(), service_key text not null, status text not null, title text not null, message text, public boolean not null default false, starts_at timestamptz not null default now(), resolved_at timestamptz, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.system_settings (setting_key text primary key, value jsonb not null default '{}', updated_by uuid references auth.users(id), updated_at timestamptz not null default now());
create table public.security_events (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), organization_id uuid references public.organizations(id), event_type text not null, severity text not null, status text not null default 'open', safe_metadata jsonb not null default '{}', resolved_by uuid references auth.users(id), resolved_at timestamptz, created_at timestamptz not null default now());
create table public.platform_audit_logs (id uuid primary key default gen_random_uuid(), actor_user_id uuid references auth.users(id), admin_role text, action text not null, entity_type text not null, entity_id text, success boolean not null, safe_metadata jsonb not null default '{}', error_code text, created_at timestamptz not null default now());
create table public.admin_saved_views (id uuid primary key default gen_random_uuid(), admin_user_id uuid not null references auth.users(id), module text not null, name text not null, filters jsonb not null default '{}', sort jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.admin_exports (id uuid primary key default gen_random_uuid(), admin_user_id uuid not null references auth.users(id), export_type text not null, format text not null, status text not null default 'pending', storage_path text, safe_filters jsonb not null default '{}', row_count integer, created_at timestamptz not null default now(), completed_at timestamptz, expires_at timestamptz);

create index support_tickets_queue_idx on public.support_tickets(status,priority,updated_at desc) where deleted_at is null; create index bugs_triage_idx on public.bugs(status,severity,updated_at desc) where deleted_at is null; create index feature_requests_public_idx on public.feature_requests(status,created_at desc) where public and deleted_at is null; create index security_events_open_idx on public.security_events(status,severity,created_at desc); create index platform_audit_created_idx on public.platform_audit_logs(created_at desc); create index cms_pages_publish_idx on public.cms_pages(slug,locale,status,published_at desc);

do $$ declare t text; begin foreach t in array array['platform_admin_roles','platform_admin_permissions','platform_admin_role_permissions','platform_admins','admin_user_notes','admin_user_tags','support_tickets','support_ticket_messages','support_ticket_attachments','support_ticket_events','support_macros','support_tags','support_ticket_tag_links','support_document_access','support_access_events','bugs','bug_comments','feature_requests','feature_votes','roadmap_items','help_categories','help_articles','help_article_feedback','cms_pages','cms_blocks','email_templates','notification_campaigns','release_notes','system_incidents','system_settings','security_events','platform_audit_logs','admin_saved_views','admin_exports'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
grant select on public.help_categories,public.help_articles,public.roadmap_items,public.release_notes to anon,authenticated;
create policy help_public on public.help_articles for select using(status='published' and published_at<=now()); create policy help_categories_public on public.help_categories for select using(true); create policy roadmap_public on public.roadmap_items for select using(public); create policy releases_public on public.release_notes for select using(public and published_at<=now());
create policy admins_self_read on public.platform_admins for select to authenticated using(user_id=(select auth.uid()) or public.has_platform_permission('admins:manage'));
create policy admin_roles_read on public.platform_admin_roles for select to authenticated using(public.has_platform_permission('admins:manage')); create policy admin_permissions_read on public.platform_admin_permissions for select to authenticated using(public.has_platform_permission('admins:manage')); create policy admin_role_permissions_read on public.platform_admin_role_permissions for select to authenticated using(public.has_platform_permission('admins:manage'));
do $$ declare t text; begin foreach t in array array['support_tickets','support_ticket_messages','support_ticket_attachments','support_ticket_events','support_macros','support_tags','support_ticket_tag_links','support_document_access','support_access_events','bugs','bug_comments'] loop execute format('create policy %I_admin_read on public.%I for select to authenticated using(public.has_platform_permission(''support:read''))',t,t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['help_categories','help_articles','cms_pages','cms_blocks','email_templates','notification_campaigns','release_notes','roadmap_items','feature_requests'] loop execute format('create policy %I_admin_manage on public.%I for all to authenticated using(public.has_platform_permission(''content:manage'')) with check(public.has_platform_permission(''content:manage''))',t,t); end loop; end $$;
create policy security_admin_read on public.security_events for select to authenticated using(public.has_platform_permission('security:read')); create policy security_admin_manage on public.security_events for update to authenticated using(public.has_platform_permission('security:manage'));
create policy audit_admin_read on public.platform_audit_logs for select to authenticated using(public.has_platform_permission('audit:read')); create policy audit_admin_insert on public.platform_audit_logs for insert to authenticated with check(actor_user_id=(select auth.uid()) and public.has_platform_permission('audit:read'));
create policy saved_views_own on public.admin_saved_views for all to authenticated using(admin_user_id=(select auth.uid())) with check(admin_user_id=(select auth.uid())); create policy exports_own on public.admin_exports for select to authenticated using(admin_user_id=(select auth.uid()) and public.has_platform_permission('exports:create'));
-- No UPDATE or DELETE policy exists for platform_audit_logs, support_ticket_events, support_access_events or billing history.

create table public.admin_document_types (id uuid primary key default gen_random_uuid(), slug text not null, version integer not null default 1, name text not null, category text not null, description text, icon text, status text not null default 'draft', premium boolean not null default false, beta boolean not null default false, sort_order integer not null default 0, languages text[] not null default array['hr'], capabilities jsonb not null default '{}', visibility_schema jsonb not null default '{}', form_schema jsonb not null default '{}', analytics_key text, created_by uuid references auth.users(id), created_at timestamptz not null default now(), published_at timestamptz, unique(slug,version));
create table public.ai_prompt_versions (id uuid primary key default gen_random_uuid(), prompt_key text not null, version integer not null, status text not null default 'draft', supported_document_types text[] not null default '{}', prompt_body text not null, change_description text not null, test_result jsonb not null default '{}', author_id uuid not null references auth.users(id), created_at timestamptz not null default now(), published_at timestamptz, unique(prompt_key,version));
create table public.ai_schema_versions (id uuid primary key default gen_random_uuid(), schema_key text not null, version integer not null, status text not null default 'draft', schema_definition jsonb not null, test_result jsonb not null default '{}', author_id uuid not null references auth.users(id), created_at timestamptz not null default now(), published_at timestamptz, unique(schema_key,version));
create table public.plan_versions (id uuid primary key default gen_random_uuid(), plan_id text not null references public.plans(id), version integer not null, status text not null default 'draft', definition jsonb not null, change_description text not null, effective_at timestamptz, author_id uuid not null references auth.users(id), created_at timestamptz not null default now(), unique(plan_id,version));
alter table public.admin_document_types enable row level security; alter table public.ai_prompt_versions enable row level security; alter table public.ai_schema_versions enable row level security; alter table public.plan_versions enable row level security;
create policy admin_document_types_read on public.admin_document_types for select to authenticated using(public.has_platform_permission('content:read')); create policy admin_document_types_manage on public.admin_document_types for all to authenticated using(public.has_platform_permission('content:manage')) with check(public.has_platform_permission('content:manage'));
create policy ai_prompts_read on public.ai_prompt_versions for select to authenticated using(public.has_platform_permission('ai:read')); create policy ai_prompts_manage on public.ai_prompt_versions for all to authenticated using(public.has_platform_permission('ai:manage')) with check(public.has_platform_permission('ai:manage'));
create policy ai_schemas_read on public.ai_schema_versions for select to authenticated using(public.has_platform_permission('ai:read')); create policy ai_schemas_manage on public.ai_schema_versions for all to authenticated using(public.has_platform_permission('ai:manage')) with check(public.has_platform_permission('ai:manage'));
create policy plan_versions_read on public.plan_versions for select to authenticated using(public.has_platform_permission('billing:read')); create policy plan_versions_manage on public.plan_versions for all to authenticated using(public.has_platform_permission('billing:manage')) with check(public.has_platform_permission('billing:manage'));
