-- Dokument AI project management and construction operations foundation.
-- Review and apply with `supabase db push`. Business records use soft delete; no destructive project cascades.
create type public.project_role as enum ('project_owner','project_manager','site_manager','foreman','engineer','supervisor','accountant','procurement','subcontractor_manager','worker','viewer');

alter table public.projects add column if not exists company_id uuid references public.companies(id) on delete set null, add column if not exists project_code text not null default '', add column if not exists description text not null default '', add column if not exists project_type text not null default 'other', add column if not exists priority text not null default 'normal', add column if not exists address text not null default '', add column if not exists city text not null default '', add column if not exists postal_code text not null default '', add column if not exists country text not null default '', add column if not exists latitude numeric(10,7), add column if not exists longitude numeric(10,7), add column if not exists start_date date, add column if not exists expected_end_date date, add column if not exists actual_end_date date, add column if not exists contract_value numeric(18,2) not null default 0, add column if not exists budget numeric(18,2) not null default 0, add column if not exists progress_percent numeric(5,2) not null default 0, add column if not exists health_status text not null default 'on_track', add column if not exists risk_level text not null default 'normal', add column if not exists project_manager_user_id uuid references auth.users(id) on delete set null, add column if not exists site_manager_user_id uuid references auth.users(id) on delete set null, add column if not exists foreman_user_id uuid references auth.users(id) on delete set null, add column if not exists cover_image_path text, add column if not exists archived_at timestamptz;
alter table public.project_members add column if not exists expires_at timestamptz, add column if not exists module_permissions text[] not null default '{}', add column if not exists location_ids uuid[] not null default '{}', add column if not exists read_only boolean not null default false, add column if not exists deleted_at timestamptz;
alter table public.project_phases add column if not exists parent_phase_id uuid references public.project_phases(id) on delete set null, add column if not exists code text not null default '', add column if not exists description text not null default '', add column if not exists progress_percent numeric(5,2) not null default 0, add column if not exists planned_start date, add column if not exists planned_end date, add column if not exists actual_start date, add column if not exists actual_end date, add column if not exists budget numeric(18,2) not null default 0, add column if not exists cost numeric(18,2) not null default 0, add column if not exists responsible_user_id uuid references auth.users(id) on delete set null, add column if not exists responsible_company_id uuid references public.companies(id) on delete set null, add column if not exists color_key text, add column if not exists is_visible boolean not null default true, add column if not exists updated_at timestamptz not null default now();
alter table public.project_locations rename column parent_id to parent_location_id;
alter table public.project_locations add column if not exists code text not null default '', add column if not exists description text not null default '', add column if not exists active boolean not null default true, add column if not exists updated_at timestamptz not null default now();

create or replace function public.is_project_member(pid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.project_members pm where pm.project_id=pid and pm.user_id=(select auth.uid()) and pm.deleted_at is null and (pm.expires_at is null or pm.expires_at>now())) or exists(select 1 from public.projects p where p.id=pid and public.is_org_member(p.organization_id)) $$;
create or replace function public.has_project_roles(pid uuid, roles public.project_role[]) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.project_members pm where pm.project_id=pid and pm.user_id=(select auth.uid()) and pm.deleted_at is null and (pm.expires_at is null or pm.expires_at>now()) and pm.role::text=any(roles::text[])) or exists(select 1 from public.projects p where p.id=pid and public.has_org_role(p.organization_id,array['owner','admin']::public.organization_role[])) $$;
revoke all on function public.is_project_member(uuid),public.has_project_roles(uuid,public.project_role[]) from public; grant execute on function public.is_project_member(uuid),public.has_project_roles(uuid,public.project_role[]) to authenticated;

create table public.project_tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), phase_id uuid references public.project_phases(id) on delete set null, location_id uuid references public.project_locations(id) on delete set null, parent_task_id uuid references public.project_tasks(id) on delete set null, title text not null, description text not null default '', status text not null default 'backlog', priority text not null default 'normal', task_type text not null default 'work', start_date date, due_date date, completed_at timestamptz, progress_percent numeric(5,2) not null default 0, estimated_hours numeric(10,2) not null default 0, actual_hours numeric(10,2) not null default 0, assigned_company_id uuid references public.companies(id) on delete set null, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.task_assignees (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), task_id uuid not null references public.project_tasks(id), user_id uuid references auth.users(id) on delete set null, worker_id uuid, assigned_at timestamptz not null default now(), deleted_at timestamptz);
create table public.task_dependencies (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), task_id uuid not null references public.project_tasks(id), depends_on_task_id uuid not null references public.project_tasks(id), dependency_type text not null default 'finish_to_start', lag_days integer not null default 0, created_at timestamptz not null default now(), deleted_at timestamptz, unique(task_id,depends_on_task_id));
create table public.task_comments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), task_id uuid not null references public.project_tasks(id), author_user_id uuid not null references auth.users(id), body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.task_checklist_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), task_id uuid not null references public.project_tasks(id), label text not null, completed boolean not null default false, position integer not null default 0, completed_by uuid references auth.users(id) on delete set null, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.task_time_entries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), task_id uuid not null references public.project_tasks(id), user_id uuid references auth.users(id) on delete set null, worker_id uuid, entry_date date not null, regular_hours numeric(8,2) not null default 0, overtime_hours numeric(8,2) not null default 0, note text, approved_by uuid references auth.users(id) on delete set null, approved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);

create table public.workers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), company_id uuid references public.companies(id) on delete set null, first_name text not null, last_name text not null, occupation text, job_title text, phone text, email text, status text not null default 'active', hourly_rate numeric(12,2), currency text not null default 'EUR', note text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.work_crews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, company_id uuid references public.companies(id) on delete set null, leader_worker_id uuid references public.workers(id) on delete set null, specialty text, active boolean not null default true, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.crew_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), crew_id uuid not null references public.work_crews(id), worker_id uuid not null references public.workers(id), joined_at date, left_at date, created_at timestamptz not null default now(), deleted_at timestamptz, unique(crew_id,worker_id));
create table public.worker_project_assignments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), worker_id uuid not null references public.workers(id), phase_id uuid references public.project_phases(id) on delete set null, role text, starts_on date, ends_on date, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.worker_time_entries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), worker_id uuid not null references public.workers(id), crew_id uuid references public.work_crews(id) on delete set null, entry_date date not null, arrival_time time, departure_time time, break_minutes integer not null default 0, regular_hours numeric(8,2) not null default 0, overtime_hours numeric(8,2) not null default 0, location_id uuid references public.project_locations(id) on delete set null, task_id uuid references public.project_tasks(id) on delete set null, status text not null default 'present', note text, locked_at timestamptz, approved_by uuid references auth.users(id) on delete set null, approved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.worker_skills (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), worker_id uuid not null references public.workers(id), name text not null, level text, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.worker_certifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), worker_id uuid not null references public.workers(id), name text not null, issuer text, issued_on date, expires_on date, storage_path text, created_at timestamptz not null default now(), deleted_at timestamptz);

create table public.project_materials (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), phase_id uuid references public.project_phases(id) on delete set null, location_id uuid references public.project_locations(id) on delete set null, code text not null default '', name text not null, description text, category text, unit text not null, planned_quantity numeric(20,6) not null default 0, ordered_quantity numeric(20,6) not null default 0, delivered_quantity numeric(20,6) not null default 0, used_quantity numeric(20,6) not null default 0, returned_quantity numeric(20,6) not null default 0, damaged_quantity numeric(20,6) not null default 0, minimum_quantity numeric(20,6) not null default 0, supplier_contact_id uuid references public.contacts(id) on delete set null, storage_location_id uuid, unit_price numeric(18,4) not null default 0, currency text not null default 'EUR', status text not null default 'planned', note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.material_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), request_number text not null, request_date date not null, phase_id uuid references public.project_phases(id) on delete set null, location_id uuid references public.project_locations(id) on delete set null, requested_by uuid not null references auth.users(id), approved_by uuid references auth.users(id) on delete set null, priority text not null default 'normal', needed_on date, status text not null default 'draft', note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, unique(project_id,request_number));
create table public.material_request_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), request_id uuid not null references public.material_requests(id), material_id uuid references public.project_materials(id) on delete set null, name text not null, requested_quantity numeric(20,6) not null, approved_quantity numeric(20,6) not null default 0, ordered_quantity numeric(20,6) not null default 0, delivered_quantity numeric(20,6) not null default 0, unit text not null, reason text, task_id uuid references public.project_tasks(id) on delete set null, note text, status text not null default 'requested', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.material_deliveries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), delivery_number text not null, supplier_contact_id uuid references public.contacts(id) on delete set null, delivery_note_number text, delivered_at timestamptz not null, driver_name text, vehicle_registration text, received_by uuid references auth.users(id) on delete set null, unloading_location text, status text not null default 'received', note text, signature_path text, document_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.material_delivery_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), delivery_id uuid not null references public.material_deliveries(id), material_id uuid references public.project_materials(id) on delete set null, ordered_quantity numeric(20,6) not null default 0, delivered_quantity numeric(20,6) not null default 0, rejected_quantity numeric(20,6) not null default 0, damaged_quantity numeric(20,6) not null default 0, accepted_quantity numeric(20,6) not null default 0, unit text not null, note text, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.project_storage_locations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), name text not null, code text not null, location_id uuid references public.project_locations(id) on delete set null, responsible_user_id uuid references auth.users(id) on delete set null, kind text, active boolean not null default true, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, unique(project_id,code));
create table public.material_stock_movements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), material_id uuid not null references public.project_materials(id), storage_location_id uuid references public.project_storage_locations(id) on delete set null, movement_type text not null, quantity numeric(20,6) not null, occurred_at timestamptz not null default now(), reference_type text, reference_id uuid, note text, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), deleted_at timestamptz);

create table public.equipment (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, category text, inventory_number text, serial_number text, owner_company_id uuid references public.companies(id) on delete set null, supplier_contact_id uuid references public.contacts(id) on delete set null, status text not null default 'available', current_location text, acquired_on date, rental_from date, rental_until date, rental_price numeric(18,2) not null default 0, currency text not null default 'EUR', last_service date, next_service date, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.equipment_project_assignments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), equipment_id uuid not null references public.equipment(id), task_id uuid references public.project_tasks(id) on delete set null, operator_worker_id uuid references public.workers(id) on delete set null, assigned_from timestamptz, assigned_until timestamptz, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.equipment_usage (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), equipment_id uuid not null references public.equipment(id), usage_date date not null, hours numeric(10,2) not null default 0, fuel_quantity numeric(12,3), task_id uuid references public.project_tasks(id) on delete set null, operator_worker_id uuid references public.workers(id) on delete set null, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.equipment_maintenance (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), equipment_id uuid not null references public.equipment(id), project_id uuid references public.projects(id) on delete set null, maintenance_type text not null, status text not null default 'planned', scheduled_on date, completed_on date, cost numeric(18,2) not null default 0, currency text not null default 'EUR', provider text, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);

create table public.cost_categories (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, code text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.project_costs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), cost_date date not null, name text not null, description text, category_id uuid references public.cost_categories(id) on delete set null, category text, supplier_contact_id uuid references public.contacts(id) on delete set null, document_number text, quantity numeric(20,6) not null default 1, unit text, unit_price numeric(18,4) not null default 0, subtotal numeric(18,2) not null default 0, tax numeric(18,2) not null default 0, total numeric(18,2) not null default 0, currency text not null default 'EUR', phase_id uuid references public.project_phases(id) on delete set null, location_id uuid references public.project_locations(id) on delete set null, task_id uuid references public.project_tasks(id) on delete set null, status text not null default 'planned', paid boolean not null default false, note text, attachment_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.project_budgets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), name text not null, version integer not null default 1, status text not null default 'draft', currency text not null default 'EUR', approved_by uuid references auth.users(id) on delete set null, approved_at timestamptz, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, unique(project_id,version));
create table public.budget_lines (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), budget_id uuid not null references public.project_budgets(id), category_id uuid references public.cost_categories(id) on delete set null, phase_id uuid references public.project_phases(id) on delete set null, location_id uuid references public.project_locations(id) on delete set null, task_id uuid references public.project_tasks(id) on delete set null, planned numeric(18,2) not null default 0, committed numeric(18,2) not null default 0, incurred numeric(18,2) not null default 0, invoiced numeric(18,2) not null default 0, paid numeric(18,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);

create table public.project_issues (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), kind text not null default 'issue', title text not null, description text not null default '', category text, location_id uuid references public.project_locations(id) on delete set null, phase_id uuid references public.project_phases(id) on delete set null, priority text not null default 'normal', status text not null default 'open', responsible_user_id uuid references auth.users(id) on delete set null, responsible_company_id uuid references public.companies(id) on delete set null, occurred_on date, due_date date, schedule_impact_days integer not null default 0, cost_impact numeric(18,2) not null default 0, resolution text, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.project_risks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), name text not null, description text, probability integer not null default 1 check(probability between 1 and 5), impact integer not null default 1 check(impact between 1 and 5), mitigation text, owner_user_id uuid references auth.users(id) on delete set null, status text not null default 'open', review_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.project_meetings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), title text not null, meeting_type text not null, starts_at timestamptz not null, location text, organizer_user_id uuid references auth.users(id) on delete set null, status text not null default 'scheduled', note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.meeting_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), meeting_id uuid not null references public.project_meetings(id), item_type text not null, title text not null, body text, responsible_user_id uuid references auth.users(id) on delete set null, due_date date, task_id uuid references public.project_tasks(id) on delete set null, status text not null default 'open', position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.project_photos (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), title text, description text, taken_at timestamptz, author_user_id uuid references auth.users(id) on delete set null, phase_id uuid references public.project_phases(id) on delete set null, location_id uuid references public.project_locations(id) on delete set null, task_id uuid references public.project_tasks(id) on delete set null, issue_id uuid references public.project_issues(id) on delete set null, category text, visibility text not null default 'project', tags text[] not null default '{}', storage_path text not null, original_storage_path text, position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.project_milestones (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), name text not null, description text, milestone_date date not null, status text not null default 'planned', responsible_user_id uuid references auth.users(id) on delete set null, completion_condition text, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.project_calendar_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), title text not null, event_type text not null, starts_at timestamptz not null, ends_at timestamptz, task_id uuid references public.project_tasks(id) on delete set null, document_id uuid references public.documents(id) on delete set null, color_key text, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);

create table public.approval_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid references public.projects(id) on delete set null, entity_type text not null, entity_id uuid not null, status text not null default 'draft', submitted_by uuid references auth.users(id) on delete set null, submitted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.approval_steps (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid references public.projects(id) on delete set null, request_id uuid not null references public.approval_requests(id), position integer not null, approver_user_id uuid references auth.users(id) on delete set null, status text not null default 'pending', comment text, decided_at timestamptz, created_at timestamptz not null default now(), deleted_at timestamptz);
create table public.checklist_templates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, category text, definition jsonb not null default '[]', is_default boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.project_checklists (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), template_id uuid references public.checklist_templates(id) on delete set null, name text not null, category text, responsible_user_id uuid references auth.users(id) on delete set null, due_date date, status text not null default 'open', signature_path text, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.project_templates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, definition jsonb not null, is_default boolean not null default false, created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, deleted_at timestamptz);
create table public.project_activity_feed (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), project_id uuid not null references public.projects(id), actor_user_id uuid references auth.users(id) on delete set null, activity_type text not null, entity_type text, entity_id uuid, safe_metadata jsonb not null default '{}', created_at timestamptz not null default now());

alter table public.documents add column if not exists project_phase_id uuid references public.project_phases(id) on delete set null, add column if not exists project_location_id uuid references public.project_locations(id) on delete set null;
create index project_tasks_project_status_due_idx on public.project_tasks(project_id,status,due_date) where deleted_at is null;
create index worker_time_project_date_idx on public.worker_time_entries(project_id,entry_date desc) where deleted_at is null;
create index materials_project_status_idx on public.project_materials(project_id,status) where deleted_at is null;
create index costs_project_date_idx on public.project_costs(project_id,cost_date desc) where deleted_at is null;
create index issues_project_status_due_idx on public.project_issues(project_id,status,due_date) where deleted_at is null;
create index photos_project_taken_idx on public.project_photos(project_id,taken_at desc) where deleted_at is null;
create index activity_project_created_idx on public.project_activity_feed(project_id,created_at desc);

do $$ declare t text; begin foreach t in array array['project_tasks','task_assignees','task_dependencies','task_comments','task_checklist_items','task_time_entries','worker_project_assignments','worker_time_entries','project_materials','material_requests','material_request_items','material_deliveries','material_delivery_items','project_storage_locations','material_stock_movements','equipment_project_assignments','equipment_usage','project_costs','project_budgets','budget_lines','project_issues','project_risks','project_meetings','meeting_items','project_photos','project_milestones','project_calendar_events','project_checklists','project_activity_feed'] loop execute format('alter table public.%I enable row level security',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); execute format('create policy %I_project_read on public.%I for select to authenticated using(public.is_project_member(project_id))',t,t); execute format('create policy %I_project_write on public.%I for all to authenticated using(public.has_project_roles(project_id,array[''project_owner'',''project_manager'',''site_manager'',''foreman'',''engineer'',''supervisor'',''accountant'',''procurement'',''subcontractor_manager'']::public.project_role[])) with check(public.has_project_roles(project_id,array[''project_owner'',''project_manager'',''site_manager'',''foreman'',''engineer'',''supervisor'',''accountant'',''procurement'',''subcontractor_manager'']::public.project_role[]))',t,t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['workers','work_crews','crew_members','worker_skills','worker_certifications','equipment','equipment_maintenance','cost_categories','checklist_templates','project_templates'] loop execute format('alter table public.%I enable row level security',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); execute format('create policy %I_org_read on public.%I for select to authenticated using(public.is_org_member(organization_id))',t,t); execute format('create policy %I_org_write on public.%I for all to authenticated using(public.has_org_role(organization_id,array[''owner'',''admin'',''manager'',''editor'']::public.organization_role[])) with check(public.has_org_role(organization_id,array[''owner'',''admin'',''manager'',''editor'']::public.organization_role[]))',t,t); end loop; end $$;
alter table public.approval_requests enable row level security; alter table public.approval_steps enable row level security; grant select,insert,update,delete on public.approval_requests,public.approval_steps to authenticated;
create policy approvals_read on public.approval_requests for select to authenticated using((project_id is not null and public.is_project_member(project_id)) or public.is_org_member(organization_id));
create policy approvals_write on public.approval_requests for all to authenticated using((project_id is not null and public.has_project_roles(project_id,array['project_owner','project_manager','site_manager','supervisor','accountant','procurement']::public.project_role[])) or public.has_org_role(organization_id,array['owner','admin','manager']::public.organization_role[])) with check(public.is_org_member(organization_id));
create policy approval_steps_read on public.approval_steps for select to authenticated using((project_id is not null and public.is_project_member(project_id)) or public.is_org_member(organization_id));
create policy approval_steps_write on public.approval_steps for all to authenticated using(approver_user_id=(select auth.uid()) or (project_id is not null and public.has_project_roles(project_id,array['project_owner','project_manager']::public.project_role[]))) with check(public.is_org_member(organization_id));

-- Private project media lives under private-documents/{organization_id}/projects/{project_id}/...
-- Existing storage bucket policies enforce organization membership; signed URLs remain server-generated and short lived.
