import type{GeneratedDocument}from"@/lib/generated-document";import{createBlock}from"./registry";import type{ComposerDocument,ContentBlock,ContentBlockType}from"./types";
export const emptyComposer=():ComposerDocument=>({version:1,blocks:[],coverPage:{enabled:false,preset:"minimal"},masterPages:{first:"default-first",standard:"default",last:"default-last"},guides:{grid:false,smartGuides:true,safeMargins:true},updatedAt:new Date().toISOString()});
const normalize=(composer:ComposerDocument):ComposerDocument=>({...composer,blocks:composer.blocks.map((v,i)=>({...v,position:i,metadata:{...v.metadata,updatedAt:new Date().toISOString()}})),updatedAt:new Date().toISOString()});
export function addBlock(composer:ComposerDocument,type:ContentBlockType,index=composer.blocks.length){const block=createBlock(type,index),blocks=[...composer.blocks];blocks.splice(Math.max(0,Math.min(index,blocks.length)),0,block);return normalize({...composer,blocks})}
export function updateBlock(composer:ComposerDocument,id:string,patch:Partial<ContentBlock>){return normalize({...composer,blocks:composer.blocks.map(v=>v.id===id&&v.locked!=="readonly"?{...v,...patch,content:patch.content??v.content}:v)})}
export function duplicateBlock(composer:ComposerDocument,id:string){const index=composer.blocks.findIndex(v=>v.id===id);if(index<0)return composer;const at=new Date().toISOString(),copy={...structuredClone(composer.blocks[index]),id:crypto.randomUUID(),name:`${composer.blocks[index].name} kopija`,metadata:{...composer.blocks[index].metadata,createdAt:at,updatedAt:at,source:"user" as const}};const blocks=[...composer.blocks];blocks.splice(index+1,0,copy);return normalize({...composer,blocks})}
export function moveBlock(composer:ComposerDocument,id:string,to:number){const from=composer.blocks.findIndex(v=>v.id===id);if(from<0||composer.blocks[from].locked==="position")return composer;const blocks=[...composer.blocks],[item]=blocks.splice(from,1);blocks.splice(Math.max(0,Math.min(to,blocks.length)),0,item);return normalize({...composer,blocks})}
export function deleteBlock(composer:ComposerDocument,id:string){const block=composer.blocks.find(v=>v.id===id);return !block||block.locked==="readonly"?composer:normalize({...composer,blocks:composer.blocks.filter(v=>v.id!==id)})}
export function migrateGeneratedDocument(document:GeneratedDocument):ComposerDocument{if(document.composer?.version===1)return structuredClone(document.composer);const composer=emptyComposer(),blocks:ContentBlock[]=[];const title=createBlock("document-title",0);title.content={text:document.title};title.metadata.source="migration";blocks.push(title);for(const field of document.fields){if(!field.value)continue;const block=createBlock(field.type==="multiline"?"text":"field-value",blocks.length);block.content=field.type==="multiline"?{title:field.label,text:field.value}:{label:field.label,value:field.value};block.metadata.source="migration";blocks.push(block)}if(document.items?.length){const block=createBlock("items-table",blocks.length);block.content={columns:["Opis","Količina","Cijena","Iznos"],rows:document.items.map(v=>[v.description,v.quantity,v.price,v.amount])};block.metadata.source="migration";blocks.push(block)}if(document.totals){const block=createBlock("financial-summary",blocks.length);block.content={subtotal:document.totals.subtotal,taxRate:document.totals.taxRate,tax:document.totals.tax,total:document.totals.total};block.metadata.source="migration";blocks.push(block)}return normalize({...composer,blocks})}
