export const contentBlockTypes=["document-title","subtitle","text","rich-text","field-value","data-list","company","customer","supplier","project","items-table","table","financial-summary","terms","note","warning","legal","signature","signatures","stamp","logo","image","gallery","before-after","attachment","checklist","timeline","stat-card","status","progress","divider","spacer","columns-2","columns-3","columns-4","qr-placeholder","barcode-placeholder","watermark","page-number","section","custom"]as const;
export type ContentBlockType=(typeof contentBlockTypes)[number];export type BlockWidth="full"|"half"|"third"|"quarter"|"30"|"40"|"60"|"70";export type BlockOutput="all"|"preview"|"pdf"|"docx"|"print"|"internal"|"customer";
export interface BlockBinding{path:string;format?:"text"|"date"|"currency"|"number"|"percent";fallback:string;manualOverride?:string;}
export interface BlockCondition{id:string;field:string;operator:"not_empty"|"empty"|"equals"|"not_equals"|"greater_than"|"less_than"|"contains";value?:string|number;}
export interface BlockStyle{variant:"plain"|"card"|"bordered"|"accent"|"callout";alignment:"left"|"center"|"right";backgroundColor?:string;textColor?:string;accentColor?:string;padding:number;borderRadius:number;}
export interface BlockLayout{width:BlockWidth;column:number;columns:1|2|3|4;}
export interface BlockPageBehavior{allowBreak:boolean;keepTogether:boolean;startOnNewPage:boolean;keepWithPrevious:boolean;keepWithNext:boolean;repeatOnEveryPage:boolean;pages:"all"|"first"|"last"|"odd"|"even";}
export interface ContentBlock{id:string;type:ContentBlockType;name:string;content:Record<string,unknown>;position:number;visible:boolean;locked:"none"|"position"|"style"|"content"|"readonly";style:BlockStyle;layout:BlockLayout;pageBehavior:BlockPageBehavior;binding?:BlockBinding;conditions:BlockCondition[];metadata:{createdAt:string;updatedAt:string;source:"system"|"migration"|"user";tags:string[]};children?:ContentBlock[];}
export interface ComposerDocument{version:1;blocks:ContentBlock[];coverPage:{enabled:boolean;preset:"corporate"|"construction"|"technical"|"minimal"|"executive"|"elegant"|"photo"|"project-report"|"cv"|"custom"};masterPages:{first:string;standard:string;last:string};guides:{grid:boolean;smartGuides:boolean;safeMargins:boolean};updatedAt:string;}
export interface ReusableBlock{id:string;organizationId?:string;name:string;category:string;tags:string[];favorite:boolean;archived:boolean;brandKitId?:string;block:ContentBlock;createdAt:string;updatedAt:string;}
export interface FormulaDefinition{operation:"sum"|"multiply"|"percent"|"average"|"min"|"max";fields:string[];percent?:number;}
export interface ComposerHistoryEntry{id:string;label:string;before:ComposerDocument;after:ComposerDocument;createdAt:string;}
