"use client";

import { useMemo, useState } from "react";
import { ContactRound, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { WorkspaceHeader } from "@/components/workspace/workspace-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useLocalSession } from "@/components/session/local-session-provider";
import { useRepositories } from "@/lib/data/use-local-data";
import type { Contact } from "@/lib/data/models";

const editable: Array<[keyof Contact,string]> = [["companyName","Naziv firme"],["contactName","Kontakt osoba"],["address","Adresa"],["city","Grad"],["postalCode","Poštanski broj"],["country","Država"],["taxNumber","OIB / PIB"],["email","Email"],["phone","Telefon"]];
function blank(userId:string): Contact { const now = new Date().toISOString(); return { id:"",userId,companyName:"",contactName:"",address:"",city:"",postalCode:"",country:"Hrvatska",taxNumber:"",email:"",phone:"",note:"",createdAt:now,updatedAt:now }; }
function ContactForm({ initial, onSave, onCancel }: { initial: Contact; onSave:(contact:Contact)=>void; onCancel:()=>void }) { const [value,setValue] = useState(initial); return <form onSubmit={(event) => { event.preventDefault(); onSave(value); }} className="rounded-3xl border bg-card p-6"><h2 className="font-semibold">{value.id ? "Uredi kontakt" : "Novi kontakt"}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{editable.map(([key,label]) => <div key={key}><label htmlFor={`contact-${key}`} className="mb-2 block text-sm font-semibold">{label}</label><Input id={`contact-${key}`} value={String(value[key])} onChange={(event) => setValue((current) => ({...current,[key]:event.target.value}))} required={key === "companyName"} /></div>)}<div className="sm:col-span-2"><label htmlFor="contact-note" className="mb-2 block text-sm font-semibold">Napomena</label><Textarea id="contact-note" value={value.note} onChange={(event) => setValue((current) => ({...current,note:event.target.value}))} /></div></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onCancel}>Odustani</Button><Button type="submit">Spremi kontakt</Button></div></form>; }

export function ContactsPage() { const repositories = useRepositories(); const { user } = useLocalSession(); const [query,setQuery] = useState(""); const [editing,setEditing] = useState<Contact | null>(null); const [version,refresh] = useState(0); const contacts = useMemo(() => { void version; return repositories?.contacts.list(user.id).filter((item) => `${item.companyName} ${item.contactName} ${item.email}`.toLocaleLowerCase("hr").includes(query.toLocaleLowerCase("hr"))) ?? []; },[query,repositories,user.id,version]); if (!repositories) return <><WorkspaceHeader title="Kontakti" /><div className="skeleton mx-auto mt-10 h-96 max-w-6xl rounded-3xl" /></>; return <><WorkspaceHeader title="Kontakti" /><main className="mx-auto max-w-6xl px-4 py-8 sm:px-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Lokalni adresar</p><h1 className="mt-2 text-3xl font-semibold">Kontakti</h1><p className="mt-2 text-muted-foreground">Odabrani kontakt može automatski popuniti podatke klijenta.</p></div><Button onClick={() => setEditing(blank(user.id))}><Plus className="size-4" /> Dodaj kontakt</Button></div>{editing && <div className="mt-7"><ContactForm key={editing.id || "new"} initial={editing} onCancel={() => setEditing(null)} onSave={(contact) => { repositories.contacts.save(contact); setEditing(null); refresh((v)=>v+1); }} /></div>}<div className="relative mt-7 max-w-xl"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Pretraži kontakte…" className="pl-9" /></div>{contacts.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{contacts.map((contact) => <article key={contact.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><span className="rounded-xl bg-primary/10 p-2 text-primary"><ContactRound className="size-5" /></span><div className="flex"><Button variant="ghost" size="icon" onClick={() => setEditing(contact)} aria-label="Uredi"><Pencil className="size-4" /></Button><Button variant="ghost" size="icon" onClick={() => { repositories.contacts.delete(contact.id); refresh((v)=>v+1); }} aria-label="Obriši"><Trash2 className="size-4 text-red-500" /></Button></div></div><h2 className="mt-4 font-semibold">{contact.companyName}</h2><p className="mt-1 text-sm text-muted-foreground">{contact.contactName || "Bez kontakt osobe"}</p><p className="mt-4 text-sm">{contact.city}, {contact.country}</p><p className="mt-1 text-xs text-muted-foreground">{contact.email}</p></article>)}</div> : <div className="mt-7 rounded-3xl border border-dashed p-12 text-center"><ContactRound className="mx-auto size-9 text-primary" /><h2 className="mt-3 font-semibold">Nema kontakata</h2><p className="mt-1 text-sm text-muted-foreground">Dodajte prvi kontakt ili promijenite pretragu.</p></div>}</main></>; }
